// ============================================================
// ULTRANOS — SHARED ENUMS
// All ENUM types used across the platform. Source of truth.
// ============================================================

export enum UserRole {
  DOCTOR = 'DOCTOR',
  PHARMACIST = 'PHARMACIST',
  LAB_TECH = 'LAB_TECH',
  PATIENT = 'PATIENT',
  GUARDIAN = 'GUARDIAN',
  SYSTEM = 'SYSTEM',
  ADMIN = 'ADMIN',
}

export enum AuditAction {
  READ = 'READ',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE_REQUEST = 'DELETE_REQUEST',
  CONSENT_GRANT = 'CONSENT_GRANT',
  CONSENT_REVOKE = 'CONSENT_REVOKE',
  SYNC = 'SYNC',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  MFA_FAIL = 'MFA_FAIL',
  BREAK_GLASS = 'BREAK_GLASS',
  EXPORT = 'EXPORT',
  PHI_READ = 'PHI_READ',
  PHI_WRITE = 'PHI_WRITE',
  SECURITY_VIOLATION = 'SECURITY_VIOLATION',
  DUPLICATE_DISPENSE_ATTEMPT = 'DUPLICATE_DISPENSE_ATTEMPT',
  KYC_SUBMITTED = 'KYC_SUBMITTED',
  LICENSE_RENEWED = 'LICENSE_RENEWED',
  LICENSE_EXPIRED_AUTO_SUSPENDED = 'LICENSE_EXPIRED_AUTO_SUSPENDED',
  LICENSE_EXPIRY_NOTIFICATION = 'LICENSE_EXPIRY_NOTIFICATION',
  LAB_APPROVED = 'LAB_APPROVED',
  LAB_SUSPENDED = 'LAB_SUSPENDED',
  LAB_REACTIVATED = 'LAB_REACTIVATED',
  ANOMALY_ALERT_DISMISSED = 'ANOMALY_ALERT_DISMISSED',
  ANOMALY_ALERT_ESCALATED = 'ANOMALY_ALERT_ESCALATED',
  ANOMALY_PROVIDER_SUSPENDED = 'ANOMALY_PROVIDER_SUSPENDED',
  KYC_APPROVED = 'KYC_APPROVED',
  KYC_REJECTED = 'KYC_REJECTED',
  KYC_MORE_INFO_REQUESTED = 'KYC_MORE_INFO_REQUESTED',
}

export enum AuditResourceType {
  PATIENT = 'PATIENT',
  PRESCRIPTION = 'PRESCRIPTION',
  LAB_RESULT = 'LAB_RESULT',
  CLINICAL_NOTE = 'CLINICAL_NOTE',
  OBSERVATION = 'OBSERVATION',
  ENCOUNTER = 'ENCOUNTER',
  CONSENT = 'CONSENT',
  USER_ACCOUNT = 'USER_ACCOUNT',
  NOTIFICATION = 'NOTIFICATION',
  ALLERGY = 'ALLERGY',
  MEDICATION_STATEMENT = 'MEDICATION_STATEMENT',
  MEDICATION_DISPENSE = 'MEDICATION_DISPENSE',
  KYC_SUBMISSION = 'KYC_SUBMISSION',
  PRACTITIONER = 'PRACTITIONER',
  LAB_REGISTRATION = 'LAB_REGISTRATION',
  PRESCRIBING_ANOMALY = 'PRESCRIBING_ANOMALY',
}

export enum AuditOutcome {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
  DENIED = 'DENIED',
}

export enum KycStatus {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
  REJECTED = 'REJECTED',
  REQUEST_MORE_INFO = 'REQUEST_MORE_INFO',
}

export enum ConsentPurpose {
  TREATMENT = 'TREATMENT',
  ANALYTICS = 'ANALYTICS',
  AI_PROCESSING = 'AI_PROCESSING',
  RESEARCH = 'RESEARCH',
  THIRD_PARTY_SHARE = 'THIRD_PARTY_SHARE',
}

export enum ConsentScope {
  PRESCRIPTIONS = 'PRESCRIPTIONS',
  LABS = 'LABS',
  VITALS = 'VITALS',
  CLINICAL_NOTES = 'CLINICAL_NOTES',
  FULL_RECORD = 'FULL_RECORD',
}

export enum ConsentStatus {
  ACTIVE = 'ACTIVE',
  WITHDRAWN = 'WITHDRAWN',
  EXPIRED = 'EXPIRED',
  SUPERSEDED = 'SUPERSEDED',
}

export enum GrantorRole {
  SELF = 'SELF',
  GUARDIAN = 'GUARDIAN',
  EMERGENCY_OVERRIDE = 'EMERGENCY_OVERRIDE',
}

export enum LabStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum DrugInteractionSeverity {
  CONTRAINDICATED = 'CONTRAINDICATED',
  ALLERGY_MATCH = 'ALLERGY_MATCH',
  MAJOR = 'MAJOR',
  MODERATE = 'MODERATE',
  MINOR = 'MINOR',
  NONE = 'NONE',
}

export enum SoapSource {
  MANUAL = 'MANUAL',
  AI_GENERATED = 'AI_GENERATED',
  AI_CONFIRMED = 'AI_CONFIRMED',
}

export enum PrescriptionStatus {
  ACTIVE = 'ACTIVE',
  DISPENSED = 'DISPENSED',
  PARTIALLY_DISPENSED = 'PARTIALLY_DISPENSED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum SyncTier {
  TIER_1_SAFETY_CRITICAL = 1,
  TIER_2_CLINICAL = 2,
  TIER_3_OPERATIONAL = 3,
  TIER_4_QUEUE_EVENTS = 4,
}

export enum AdministrativeGender {
  MALE = 'male',
  FEMALE = 'female',
  OTHER = 'other',
  UNKNOWN = 'unknown',
}

export enum NotificationType {
  LAB_RESULT_AVAILABLE = 'LAB_RESULT_AVAILABLE',
  LAB_RESULT_ESCALATION = 'LAB_RESULT_ESCALATION',
  PRESCRIPTION_READY = 'PRESCRIPTION_READY',
  CONSENT_CHANGE = 'CONSENT_CHANGE',
  SYNC_CONFLICT = 'SYNC_CONFLICT',
  ALLERGY_UPDATE = 'ALLERGY_UPDATE',
  LICENSE_EXPIRY_WARNING = 'LICENSE_EXPIRY_WARNING',
  LICENSE_EXPIRED = 'LICENSE_EXPIRED',
  LAB_APPROVED = 'LAB_APPROVED',
  LAB_SUSPENDED = 'LAB_SUSPENDED',
  LAB_REACTIVATED = 'LAB_REACTIVATED',
  PROVIDER_SUSPENDED = 'PROVIDER_SUSPENDED',
  KYC_APPROVED = 'KYC_APPROVED',
  KYC_REJECTED = 'KYC_REJECTED',
  KYC_MORE_INFO_REQUESTED = 'KYC_MORE_INFO_REQUESTED',
}

export enum NotificationStatus {
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  FAILED = 'FAILED',
}

export enum RecipientRole {
  CLINICIAN = 'CLINICIAN',
  PATIENT = 'PATIENT',
}
