// ============================================================
// ULTRANOS — SHARED ENUMS
// All ENUM types used across the platform. Source of truth.
// ============================================================

export enum UserRole {
  DOCTOR = 'DOCTOR',
  PHARMACIST = 'PHARMACIST',
  LAB_TECH = 'LAB_TECH',
  PATIENT = 'PATIENT',
  GUARDIAN = 'GUARDIAN',
  SYSTEM = 'SYSTEM',
  ADMIN = 'ADMIN',
}

export enum AuditAction {
  READ = 'READ',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE_REQUEST = 'DELETE_REQUEST',
  CONSENT_GRANT = 'CONSENT_GRANT',
  CONSENT_REVOKE = 'CONSENT_REVOKE',
  SYNC = 'SYNC',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  MFA_FAIL = 'MFA_FAIL',
  BREAK_GLASS = 'BREAK_GLASS',
  EXPORT = 'EXPORT',
  PHI_READ = 'PHI_READ',
  PHI_WRITE = 'PHI_WRITE',
  SECURITY_VIOLATION = 'SECURITY_VIOLATION',
  DUPLICATE_DISPENSE_ATTEMPT = 'DUPLICATE_DISPENSE_ATTEMPT',
  KYC_SUBMITTED = 'KYC_SUBMITTED',
  LICENSE_RENEWED = 'LICENSE_RENEWED',
  LICENSE_EXPIRED_AUTO_SUSPENDED = 'LICENSE_EXPIRED_AUTO_SUSPENDED',
  LICENSE_EXPIRY_NOTIFICATION = 'LICENSE_EXPIRY_NOTIFICATION',
  LAB_APPROVED = 'LAB_APPROVED',
  LAB_SUSPENDED = 'LAB_SUSPENDED',
  LAB_REACTIVATED = 'LAB_REACTIVATED',
  ANOMALY_ALERT_DISMISSED = 'ANOMALY_ALERT_DISMISSED',
  ANOMALY_ALERT_ESCALATED = 'ANOMALY_ALERT_ESCALATED',
  ANOMALY_PROVIDER_SUSPENDED = 'ANOMALY_PROVIDER_SUSPENDED',
  KYC_APPROVED = 'KYC_APPROVED',
  KYC_REJECTED = 'KYC_REJECTED',
  KYC_MORE_INFO_REQUESTED = 'KYC_MORE_INFO_REQUESTED',
  PHI_CLEANUP = 'PHI_CLEANUP',
  PATIENT_IDENTITY_VERIFIED = 'PATIENT_IDENTITY_VERIFIED',
  REFERENCE_RANGE_UPDATED = 'REFERENCE_RANGE_UPDATED',
  RESULT_AMENDED = 'RESULT_AMENDED',
  QC_DRIFT_DETECTED = 'QC_DRIFT_DETECTED',
  QC_DRIFT_ACKNOWLEDGED = 'QC_DRIFT_ACKNOWLEDGED',
  CRITICAL_VALUE_CHECKLIST_COMPLETED = 'CRITICAL_VALUE_CHECKLIST_COMPLETED',
  // Story 43.1 — Immutable Result Audit Chain lifecycle events
  SAMPLE_RECEIVED = 'SAMPLE_RECEIVED',
  SAMPLE_PROCESSED = 'SAMPLE_PROCESSED',
  RESULT_ENTERED = 'RESULT_ENTERED',
  RESULT_AUTHORIZED = 'RESULT_AUTHORIZED',
  RESULT_RELEASED = 'RESULT_RELEASED',
  RESULT_DELIVERED = 'RESULT_DELIVERED',
  // Story 49.3 — P2P Sync audit events
  P2P_SYNC = 'P2P_SYNC',
}

export enum AuditResourceType {
  PATIENT = 'PATIENT',
  PRESCRIPTION = 'PRESCRIPTION',
  LAB_RESULT = 'LAB_RESULT',
  CLINICAL_NOTE = 'CLINICAL_NOTE',
  OBSERVATION = 'OBSERVATION',
  ENCOUNTER = 'ENCOUNTER',
  CONSENT = 'CONSENT',
  USER_ACCOUNT = 'USER_ACCOUNT',
  NOTIFICATION = 'NOTIFICATION',
  ALLERGY = 'ALLERGY',
  MEDICATION_STATEMENT = 'MEDICATION_STATEMENT',
  MEDICATION_DISPENSE = 'MEDICATION_DISPENSE',
  KYC_SUBMISSION = 'KYC_SUBMISSION',
  PRACTITIONER = 'PRACTITIONER',
  LAB_REGISTRATION = 'LAB_REGISTRATION',
  PRESCRIBING_ANOMALY = 'PRESCRIBING_ANOMALY',
  SYSTEM = 'SYSTEM',
  WASTE_CONTAINER = 'WASTE_CONTAINER',
  MENTORSHIP = 'MENTORSHIP',
  EMPLOYEE_HEALTH = 'EMPLOYEE_HEALTH',
  TEMPERATURE_MONITORING = 'TEMPERATURE_MONITORING',
  SPECIMEN = 'SPECIMEN',
  // Story 43.1 — sample-scoped audit events
  LAB_SAMPLE = 'LAB_SAMPLE',
  // Story 50.2 — donor reports
  DIAGNOSTIC_REPORT = 'DIAGNOSTIC_REPORT',
  // Story 49.1 — Data Budget Mode
  DATA_BUDGET = 'DATA_BUDGET',
  REFERENCE_RANGE = 'REFERENCE_RANGE',
  PAYMENT = 'PAYMENT',
}

export enum AuditOutcome {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
  DENIED = 'DENIED',
}

export enum KycStatus {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
  REJECTED = 'REJECTED',
  REQUEST_MORE_INFO = 'REQUEST_MORE_INFO',
}

export enum ConsentPurpose {
  TREATMENT = 'TREATMENT',
  ANALYTICS = 'ANALYTICS',
  AI_PROCESSING = 'AI_PROCESSING',
  RESEARCH = 'RESEARCH',
  THIRD_PARTY_SHARE = 'THIRD_PARTY_SHARE',
}

export enum ConsentScope {
  PRESCRIPTIONS = 'PRESCRIPTIONS',
  LABS = 'LABS',
  VITALS = 'VITALS',
  CLINICAL_NOTES = 'CLINICAL_NOTES',
  FULL_RECORD = 'FULL_RECORD',
}

export enum ConsentStatus {
  ACTIVE = 'ACTIVE',
  WITHDRAWN = 'WITHDRAWN',
  EXPIRED = 'EXPIRED',
  SUPERSEDED = 'SUPERSEDED',
}

export enum GrantorRole {
  SELF = 'SELF',
  GUARDIAN = 'GUARDIAN',
  EMERGENCY_OVERRIDE = 'EMERGENCY_OVERRIDE',
}

export enum LabStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum DrugInteractionSeverity {
  CONTRAINDICATED = 'CONTRAINDICATED',
  ALLERGY_MATCH = 'ALLERGY_MATCH',
  MAJOR = 'MAJOR',
  MODERATE = 'MODERATE',
  MINOR = 'MINOR',
  NONE = 'NONE',
}

export enum SoapSource {
  MANUAL = 'MANUAL',
  AI_GENERATED = 'AI_GENERATED',
  AI_CONFIRMED = 'AI_CONFIRMED',
}

export enum PrescriptionStatus {
  ACTIVE = 'ACTIVE',
  DISPENSED = 'DISPENSED',
  PARTIALLY_DISPENSED = 'PARTIALLY_DISPENSED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum SyncTier {
  TIER_1_SAFETY_CRITICAL = 1,
  TIER_2_CLINICAL = 2,
  TIER_3_OPERATIONAL = 3,
  TIER_4_QUEUE_EVENTS = 4,
}

export enum AdministrativeGender {
  MALE = 'male',
  FEMALE = 'female',
  OTHER = 'other',
  UNKNOWN = 'unknown',
}

export enum NotificationType {
  LAB_RESULT_AVAILABLE = 'LAB_RESULT_AVAILABLE',
  LAB_RESULT_ESCALATION = 'LAB_RESULT_ESCALATION',
  PRESCRIPTION_READY = 'PRESCRIPTION_READY',
  CONSENT_CHANGE = 'CONSENT_CHANGE',
  SYNC_CONFLICT = 'SYNC_CONFLICT',
  ALLERGY_UPDATE = 'ALLERGY_UPDATE',
  LICENSE_EXPIRY_WARNING = 'LICENSE_EXPIRY_WARNING',
  LICENSE_EXPIRED = 'LICENSE_EXPIRED',
  LAB_APPROVED = 'LAB_APPROVED',
  LAB_SUSPENDED = 'LAB_SUSPENDED',
  LAB_REACTIVATED = 'LAB_REACTIVATED',
  PROVIDER_SUSPENDED = 'PROVIDER_SUSPENDED',
  KYC_APPROVED = 'KYC_APPROVED',
  KYC_REJECTED = 'KYC_REJECTED',
  KYC_MORE_INFO_REQUESTED = 'KYC_MORE_INFO_REQUESTED',
}

export enum NotificationStatus {
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  FAILED = 'FAILED',
}

export enum RecipientRole {
  CLINICIAN = 'CLINICIAN',
  PATIENT = 'PATIENT',
}

/**
 * Lab sub-roles within the LAB_TECH UserRole.
 * Story 42.1: Four-tier lab role hierarchy.
 * Ordered by privilege level (lowest → highest).
 */
export enum LabRole {
  LAB_TECH = 'LAB_TECH',
  SENIOR_TECH = 'SENIOR_TECH',
  SUPERVISOR = 'SUPERVISOR',
  LAB_MANAGER = 'LAB_MANAGER',
}

/**
 * Lab-specific permissions gated by LabRole.
 * Story 42.1 AC 2: Permission matrix.
 */
export enum LabPermission {
  ENTER_RESULTS = 'ENTER_RESULTS',
  RELEASE_ROUTINE_RESULTS = 'RELEASE_ROUTINE_RESULTS',
  RELEASE_ALL_RESULTS = 'RELEASE_ALL_RESULTS',
  OVERRIDE_QC_LOCKOUT = 'OVERRIDE_QC_LOCKOUT',
  VIEW_STAFF = 'VIEW_STAFF',
  MANAGE_STAFF_ROLES = 'MANAGE_STAFF_ROLES',
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',
}

/**
 * Methods used to verify patient identity at sample collection.
 * Story 43.4: Two-identifier minimum (WHO patient identification standard).
 * IMPORTANT: The record stores the METHOD, never the data value itself (CLAUDE.md Rule #7).
 */
export enum PatientVerificationMethod {
  NATIONAL_ID_SCANNED = 'NATIONAL_ID_SCANNED',     // Physical National ID card scanned or number entered
  VERBAL_CONFIRMATION = 'VERBAL_CONFIRMATION',       // Verbal confirmation of patient name + father's name
  QR_CODE = 'QR_CODE',                               // QR code scanned from Health Passport (Patient-Lite app)
  WRISTBAND_SCANNED = 'WRISTBAND_SCANNED',           // Hospital wristband barcode (future use)
  OTHER = 'OTHER',                                   // Requires free-text description
}

/**
 * Reason codes for lab result amendments.
 * Story 43.3 AC #3: Mandatory reason classification for amendment audit trail.
 */
export enum AmendmentReasonCode {
  CLERICAL_ERROR = 'CLERICAL_ERROR',
  INSTRUMENT_MALFUNCTION = 'INSTRUMENT_MALFUNCTION',
  WRONG_PATIENT = 'WRONG_PATIENT',
  QC_FAILURE_POST_RELEASE = 'QC_FAILURE_POST_RELEASE',
  TRANSCRIPTION_ERROR = 'TRANSCRIPTION_ERROR',
  OTHER = 'OTHER',
}
