'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { useTranslations } from 'next-intl'
import Link from 'next/link'
import { ChevronRight } from '@ultranos/ui-kit/icons'
import { LabRole } from '@ultranos/shared-types'
import { useAuthSessionStore } from '@/stores/auth-session-store'
import { useDataBudgetStore } from '@/stores/data-budget-store'
import { getSupabaseBrowserClient } from '@/lib/supabase'
import { reportDataBudgetConfigEvent } from '@/lib/audit-client'
import { Button } from '@/components/ui/Button'
import { SecurityAlertFlow } from '@/components/security/SecurityAlertFlow'
import { ConfidencePrincipleInfo } from '@/components/ai/ConfidencePrincipleInfo'
import { DEFAULT_TAT_PROFILES, type TestTatProfile } from '@/lib/test-tat-database'
import { getTatOverrides, putTatOverride, removeTatOverride, type TatOverrideEntry, getDailyLogSettings, saveDailyLogSettings, getAchievementSchedulerConfig, putAchievementSchedulerConfig, getAchievementPreferences, putAchievementPreferences, getChecklistConfig, putChecklistConfig, getAllCriticalValueThresholds, putCriticalValueThreshold, getLockTimeoutHours, getDb } from '@/lib/db'
import type { DailyLogSettings } from '@/lib/daily-log-types'
import type { ChecklistConfigItem, CriticalValueThreshold } from '@/lib/critical-values/types'
import { DEFAULT_CHECKLIST_CONFIG_ITEMS, DEFAULT_CRITICAL_THRESHOLDS } from '@/lib/critical-values/default-thresholds'
import { BadgeShowcase } from '@/components/quality/BadgeShowcase'
import { SurveillanceConfigCard } from '@/components/settings/SurveillanceConfig'
import { ProgramRegistration } from '@/components/settings/ProgramRegistration'
import { SmsGatewayConfig } from '@/components/settings/SmsGatewayConfig'

/** Map LabRole enum to i18n key under settings namespace */
const ROLE_I18N_KEY: Record<LabRole, string> = {
  [LabRole.LAB_TECH]: 'labTech',
  [LabRole.SENIOR_TECH]: 'seniorTech',
  [LabRole.SUPERVISOR]: 'supervisor',
  [LabRole.LAB_MANAGER]: 'labManager',
}

export function LabSettingsView() {
  const t = useTranslations('settings')
  const tScheduler = useTranslations('scheduler.nav')
  const tData = useTranslations('dataBudget')
  const tSecurity = useTranslations('security')
  const tChecklist = useTranslations('criticalValueChecklist')
  const session = useAuthSessionStore((s) => s.session)
  const [showSecurityAlert, setShowSecurityAlert] = useState(false)
  const isManager = session?.labRole === LabRole.LAB_MANAGER
  const {
    planSizeMB,
    billingCycleDay,
    lowDataMode,
    isLoaded,
    loadFromDexie,
    updateConfig,
  } = useDataBudgetStore()

  // TAT override state (Task 6 — Story 45.5)
  const [tatOverrides, setTatOverrides] = useState<Partial<Record<string, TatOverrideEntry>>>({})
  const [tatEdits, setTatEdits] = useState<Record<string, number>>({})

  // Daily Report settings state (Story 50.4)
  const tDaily = useTranslations('dailyLog')
  const [dailySettings, setDailySettings] = useState<DailyLogSettings>({
    id: 'config',
    autoTriggerTime: '17:00',
    lastAutoGenerateDate: '',
    facilityName: 'Lab Lite',
    watermarkText: 'ULTRANOS VERIFIED',
  })

  useEffect(() => {
    getDailyLogSettings().then(setDailySettings).catch(() => {})
  }, [])

  async function handleDailySettingChange<K extends keyof DailyLogSettings>(key: K, value: DailyLogSettings[K]) {
    const updated = { ...dailySettings, [key]: value }
    setDailySettings(updated)
    await saveDailyLogSettings(updated)
  }

  // Critical Value Checklist + Threshold config state (Story 43.7)
  const [checklistItems, setChecklistItems] = useState<ChecklistConfigItem[]>(DEFAULT_CHECKLIST_CONFIG_ITEMS)
  const [thresholds, setThresholds] = useState<CriticalValueThreshold[]>([])
  const [newChecklistLabel, setNewChecklistLabel] = useState('')

  useEffect(() => {
    async function loadCriticalValueConfig() {
      try {
        const config = await getChecklistConfig()
        if (config?.items?.length) setChecklistItems(config.items)
        const savedThresholds = await getAllCriticalValueThresholds()
        if (savedThresholds.length > 0) setThresholds(savedThresholds)
        else {
          // First load — show defaults
          setThresholds(DEFAULT_CRITICAL_THRESHOLDS as CriticalValueThreshold[])
        }
      } catch {
        // non-fatal — fall back to defaults
      }
    }
    void loadCriticalValueConfig()
  }, [])

  async function handleToggleChecklistItemRequired(id: string) {
    const updated = checklistItems.map((item) =>
      item.id === id ? { ...item, isRequired: !item.isRequired } : item,
    )
    setChecklistItems(updated)
    await putChecklistConfig({
      id: 'config',
      labId: session?.labId ?? 'default',
      items: updated,
      updatedAt: new Date().toISOString(),
      updatedBy: session?.userId ?? 'unknown',
    })
  }

  async function handleAddChecklistItem() {
    const label = newChecklistLabel.trim()
    if (!label) return
    const newItem: ChecklistConfigItem = {
      id: crypto.randomUUID(),
      label,
      isRequired: false,
      isDefault: false,
      order: checklistItems.length + 1,
    }
    const updated = [...checklistItems, newItem]
    setChecklistItems(updated)
    setNewChecklistLabel('')
    await putChecklistConfig({
      id: 'config',
      labId: session?.labId ?? 'default',
      items: updated,
      updatedAt: new Date().toISOString(),
      updatedBy: session?.userId ?? 'unknown',
    })
  }

  async function handleRemoveChecklistItem(id: string) {
    const updated = checklistItems.filter((item) => item.id !== id)
    setChecklistItems(updated)
    await putChecklistConfig({
      id: 'config',
      labId: session?.labId ?? 'default',
      items: updated,
      updatedAt: new Date().toISOString(),
      updatedBy: session?.userId ?? 'unknown',
    })
  }

  async function handleSaveThreshold(threshold: CriticalValueThreshold) {
    await putCriticalValueThreshold({
      ...threshold,
      configuredBy: session?.userId ?? 'lab',
      updatedAt: new Date().toISOString(),
    })
    // Reload
    const saved = await getAllCriticalValueThresholds()
    setThresholds(saved.length > 0 ? saved : (DEFAULT_CRITICAL_THRESHOLDS as CriticalValueThreshold[]))
  }

  // Lock timeout state (Story 51.3 AC #7)
  const [lockTimeoutHours, setLockTimeoutHours] = useState(4)

  useEffect(() => {
    getLockTimeoutHours().then(setLockTimeoutHours).catch(() => {})
  }, [])

  async function handleLockTimeoutChange(hours: number) {
    setLockTimeoutHours(hours)
    try {
      const db = getDb()
      await db.lab_config.put({ id: 'lockTimeoutHours', value: String(hours) })
    } catch {
      // non-fatal — best-effort save
    }
  }

  // Gamification state (Story 51.7)
  const [gamificationEnabled, setGamificationEnabled] = useState(false)
  const [showOnTeamDashboard, setShowOnTeamDashboard] = useState(true)

  useEffect(() => {
    async function loadGamification() {
      try {
        const config = await getAchievementSchedulerConfig()
        setGamificationEnabled(config.gamificationEnabled)
        if (session?.practitionerId) {
          const prefs = await getAchievementPreferences(session.practitionerId)
          setShowOnTeamDashboard(prefs.showOnTeamDashboard)
        }
      } catch {
        // non-fatal
      }
    }
    void loadGamification()
  }, [session?.practitionerId])

  async function handleGamificationToggle(enabled: boolean) {
    setGamificationEnabled(enabled)
    try {
      const config = await getAchievementSchedulerConfig()
      await putAchievementSchedulerConfig({ ...config, gamificationEnabled: enabled })
    } catch {
      // non-fatal — toggle is best-effort
    }
  }

  async function handleShowOnDashboardToggle(show: boolean) {
    if (!session?.practitionerId) return
    setShowOnTeamDashboard(show)
    try {
      await putAchievementPreferences({
        techId: session.practitionerId,
        showOnTeamDashboard: show,
      })
    } catch {
      // non-fatal
    }
  }

  useEffect(() => {
    if (!isLoaded) void loadFromDexie()
  }, [isLoaded, loadFromDexie])

  useEffect(() => {
    getTatOverrides().then((overrides) => {
      setTatOverrides(overrides)
      const edits: Record<string, number> = {}
      for (const p of DEFAULT_TAT_PROFILES) {
        edits[p.loincCode] = overrides[p.loincCode]?.estimatedMinutes ?? p.estimatedMinutes
      }
      setTatEdits(edits)
    })
  }, [])

  async function handleSaveTatOverride(profile: TestTatProfile, newMinutes: number) {
    const entry: TatOverrideEntry = {
      ...profile,
      estimatedMinutes: newMinutes,
      updatedAt: new Date().toISOString(),
    }
    await putTatOverride(entry)
    setTatOverrides((prev) => ({ ...prev, [profile.loincCode]: entry }))
  }

  async function handleResetTatOverride(loincCode: string) {
    await removeTatOverride(loincCode)
    const defaultProfile = DEFAULT_TAT_PROFILES.find((p) => p.loincCode === loincCode)
    setTatOverrides((prev) => {
      const next = { ...prev }
      delete next[loincCode]
      return next
    })
    if (defaultProfile) {
      setTatEdits((prev) => ({ ...prev, [loincCode]: defaultProfile.estimatedMinutes }))
    }
  }

  const handleSignOut = useCallback(async () => {
    useAuthSessionStore.getState().clearSession()
    await getSupabaseBrowserClient().auth.signOut()
    window.location.href = '/login'
  }, [])

  return (
    <div className="mx-auto max-w-3xl px-4 py-6">
      <h1 className="text-2xl font-bold text-foreground mb-6">{t('title')}</h1>

      <div className="flex flex-col gap-4">
        {/* Profile Card */}
        <div className="rounded-lg border border-border bg-card p-4">
          <h2 className="text-sm font-semibold text-muted-foreground mb-3">{t('profile')}</h2>
          <dl className="space-y-2">
            <div className="flex justify-between">
              <dt className="text-sm text-muted-foreground">{t('email')}</dt>
              <dd className="text-sm font-medium text-foreground">{session?.email ?? '--'}</dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-sm text-muted-foreground">{t('role')}</dt>
              <dd>
                <span className="inline-flex rounded-full bg-blue-50 px-2.5 py-0.5 text-xs font-medium text-blue-700">
                  {session?.labRole
                    ? t(ROLE_I18N_KEY[session.labRole as LabRole] ?? 'labTech')
                    : t('labTech')}
                </span>
              </dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-sm text-muted-foreground">{t('practitionerId')}</dt>
              <dd className="text-sm font-medium text-foreground font-mono">
                {session?.practitionerId
                  ? session.practitionerId.slice(0, 8)
                  : '--'}
              </dd>
            </div>
          </dl>
        </div>

        {/* Quality Badges — Story 46.7 */}
        <div className="rounded-lg border border-border bg-card p-4">
          <BadgeShowcase />
        </div>

        {/* Lab Info Card */}
        <div className="rounded-lg border border-border bg-card p-4">
          <h2 className="text-sm font-semibold text-muted-foreground mb-3">{t('labInfo')}</h2>
          <dl className="space-y-2">
            <div className="flex justify-between">
              <dt className="text-sm text-muted-foreground">{t('labName')}</dt>
              <dd className="text-sm font-medium text-foreground">
                {/* labName is used in LabIdentityCard via session but not in AuthSession interface */}
                {(session as Record<string, unknown>)?.labName as string ?? 'Lab'}
              </dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-sm text-muted-foreground">{t('accreditation')}</dt>
              <dd className="text-sm text-muted-foreground">--</dd>
            </div>
          </dl>
        </div>

        {/* Data & Connectivity */}
        <div className="rounded-lg border border-border bg-card p-4">
          <h2 className="text-sm font-semibold text-muted-foreground mb-3">{tData('settingsTitle')}</h2>
          <div className="space-y-3">
            {/* Plan size */}
            <div className="flex items-center justify-between">
              <label htmlFor="planSizeMB" className="text-sm text-muted-foreground">
                {tData('planSize')}
              </label>
              <input
                id="planSizeMB"
                type="number"
                min={1}
                max={99999}
                value={planSizeMB}
                onChange={(e) => {
                  const val = parseInt(e.target.value, 10)
                  if (!isNaN(val) && val > 0) {
                    const old = String(planSizeMB)
                    void updateConfig({ planSizeMB: val })
                    reportDataBudgetConfigEvent({
                      action: 'DATA_BUDGET_CONFIG_UPDATED',
                      field: 'planSizeMB',
                      oldValue: old,
                      newValue: String(val),
                    })
                  }
                }}
                className="w-24 rounded border border-border px-2 py-1 text-sm text-end"
              />
            </div>

            {/* Billing cycle day */}
            <div className="flex items-center justify-between">
              <label htmlFor="billingCycleDay" className="text-sm text-muted-foreground">
                {tData('billingCycleDay')}
              </label>
              <select
                id="billingCycleDay"
                value={billingCycleDay}
                onChange={(e) => {
                  const val = parseInt(e.target.value, 10)
                  const old = String(billingCycleDay)
                  void updateConfig({ billingCycleDay: val })
                  reportDataBudgetConfigEvent({
                    action: 'DATA_BUDGET_CONFIG_UPDATED',
                    field: 'billingCycleDay',
                    oldValue: old,
                    newValue: String(val),
                  })
                }}
                className="w-24 rounded border border-border px-2 py-1 text-sm"
              >
                {Array.from({ length: 28 }, (_, i) => i + 1).map((d) => (
                  <option key={d} value={d}>{d}</option>
                ))}
              </select>
            </div>

            {/* Low Data Mode toggle */}
            <div className="flex items-center justify-between">
              <div>
                <span className="text-sm text-muted-foreground">{tData('lowDataMode')}</span>
                <p className="text-xs text-muted-foreground">{tData('lowDataModeDesc')}</p>
              </div>
              <button
                type="button"
                role="switch"
                aria-checked={lowDataMode}
                onClick={() => {
                  const old = String(lowDataMode)
                  const next = !lowDataMode
                  void updateConfig({ lowDataMode: next })
                  reportDataBudgetConfigEvent({
                    action: 'DATA_BUDGET_CONFIG_UPDATED',
                    field: 'lowDataMode',
                    oldValue: old,
                    newValue: String(next),
                  })
                }}
                className={`relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full transition-colors ${
                  lowDataMode ? 'bg-blue-600' : 'bg-muted'
                }`}
              >
                <span
                  className={`pointer-events-none inline-block h-5 w-5 transform rounded-full bg-card shadow transition-transform mt-0.5 ${
                    lowDataMode ? 'translate-x-5 ms-0.5' : 'translate-x-0.5'
                  }`}
                />
              </button>
            </div>

            {/* Link to full dashboard */}
            <Link
              href="/settings/data-budget"
              className="block text-sm text-blue-600 hover:text-blue-700 mt-2"
            >
              {tData('viewDashboard')} &rarr;
            </Link>
          </div>
        </div>

        {/* Turnaround Times — Task 6, Story 45.5 */}
        <div
          className="rounded-lg border border-border bg-card p-4"
          data-testid="tat-settings-section"
        >
          <h2 className="text-sm font-semibold text-muted-foreground mb-3">
            {t('turnaroundTimes')}
          </h2>
          <div className="space-y-2">
            {DEFAULT_TAT_PROFILES.map((profile) => {
              const currentMinutes = tatEdits[profile.loincCode] ?? profile.estimatedMinutes
              const isOverridden = !!tatOverrides[profile.loincCode]
              return (
                <div key={profile.loincCode} className="flex items-center justify-between gap-2">
                  <span className="text-sm text-foreground flex-1">{profile.loincDisplay}</span>
                  {isManager ? (
                    <div className="flex items-center gap-2">
                      <input
                        type="number"
                        min={1}
                        max={9999}
                        value={currentMinutes}
                        data-testid={`tat-input-${profile.loincCode}`}
                        onChange={(e) => {
                          const val = parseInt(e.target.value, 10)
                          if (!isNaN(val) && val > 0) {
                            setTatEdits((prev) => ({ ...prev, [profile.loincCode]: val }))
                          }
                        }}
                        onBlur={async () => {
                          const val = tatEdits[profile.loincCode]
                          if (val !== undefined && val !== profile.estimatedMinutes) {
                            await handleSaveTatOverride(profile, val)
                          }
                        }}
                        className="w-20 rounded border border-border px-2 py-1 text-sm text-end"
                      />
                      <span className="text-xs text-muted-foreground">{t('min')}</span>
                      {isOverridden && (
                        <button
                          type="button"
                          data-testid={`tat-reset-${profile.loincCode}`}
                          onClick={() => handleResetTatOverride(profile.loincCode)}
                          className="text-xs text-blue-600 hover:text-blue-700"
                        >
                          {t('tatReset')}
                        </button>
                      )}
                    </div>
                  ) : (
                    <span
                      className="text-sm font-medium text-foreground"
                      data-testid={`tat-display-${profile.loincCode}`}
                    >
                      {currentMinutes} {t('min')}
                    </span>
                  )}
                </div>
              )
            })}
          </div>
        </div>

        {/* Lock Timeout — Story 51.3 AC #7 — lab_manager only */}
        {isManager && (
          <div
            className="rounded-lg border border-border bg-card p-4"
            data-testid="lock-timeout-settings"
          >
            <h2 className="text-sm font-semibold text-muted-foreground mb-1">
              {t('lockTimeout')}
            </h2>
            <p className="text-xs text-muted-foreground mb-3">{t('lockTimeoutDesc')}</p>
            <div className="flex items-center gap-3">
              <input
                id="lock-timeout-hours"
                type="number"
                min={1}
                max={24}
                value={lockTimeoutHours}
                onChange={(e) => {
                  const val = parseInt(e.target.value, 10)
                  if (!isNaN(val) && val >= 1 && val <= 24) {
                    void handleLockTimeoutChange(val)
                  }
                }}
                className="w-20 rounded border border-border px-2 py-1 text-sm text-end"
                data-testid="lock-timeout-input"
              />
              <label htmlFor="lock-timeout-hours" className="text-sm text-muted-foreground">
                {t('hours')}
              </label>
            </div>
          </div>
        )}

        {/* Supplier Configuration — Story 48.2 (P25: nav entry required for route to be reachable) */}
        <Link
          href="/settings/suppliers"
          data-testid="supplier-config-link"
          className="rounded-lg border border-border bg-card p-4 flex items-center justify-between hover:bg-muted/30 transition-colors"
        >
          <div>
            <h2 className="text-sm font-semibold text-muted-foreground">{tScheduler('supplierConfig')}</h2>
            <p className="text-xs text-muted-foreground mt-0.5">
              {tScheduler('supplierConfigDesc')}
            </p>
          </div>
          <ChevronRight size={20} className="text-muted-foreground rtl:-scale-x-100" aria-hidden="true" />
        </Link>

        {/* Power & Scheduling */}
        <Link
          href="/settings/power-schedule"
          className="rounded-lg border border-border bg-card p-4 flex items-center justify-between hover:bg-muted/30 transition-colors"
        >
          <div>
            <h2 className="text-sm font-semibold text-muted-foreground">{tScheduler('powerScheduling')}</h2>
            <p className="text-xs text-muted-foreground mt-0.5">
              Generator schedule &amp; test time estimates
            </p>
          </div>
          <ChevronRight size={20} className="text-muted-foreground rtl:-scale-x-100" aria-hidden="true" />
        </Link>

        {/* Reference Ranges — Story 43.8 (AC #1) */}
        <Link
          href="/settings/reference-ranges"
          data-testid="reference-ranges-link"
          className="rounded-lg border border-border bg-card p-4 flex items-center justify-between hover:bg-muted/30 transition-colors"
        >
          <div>
            <h2 className="text-sm font-semibold text-muted-foreground">{t('referenceRanges')}</h2>
            <p className="text-xs text-muted-foreground mt-0.5">
              {t('referenceRangesDesc')}
            </p>
          </div>
          <ChevronRight size={20} className="text-muted-foreground rtl:-scale-x-100" aria-hidden="true" />
        </Link>

        {/* Critical Value Checklist Config — Story 43.7 (AC #4) — lab_manager only */}
        {isManager && (
          <div
            className="rounded-lg border border-border bg-card p-4"
            data-testid="critical-value-checklist-settings"
          >
            <h2 className="text-sm font-semibold text-muted-foreground mb-1">
              {tChecklist('settingsTitle')}
            </h2>
            <p className="text-xs text-muted-foreground mb-3">{tChecklist('settingsDescription')}</p>
            <div className="space-y-2">
              {checklistItems.map((item) => (
                <div key={item.id} className="flex items-center justify-between gap-2">
                  <span className="text-sm text-foreground flex-1">{item.label}</span>
                  <div className="flex items-center gap-2 shrink-0">
                    <button
                      type="button"
                      onClick={() => void handleToggleChecklistItemRequired(item.id)}
                      className={`rounded px-2 py-0.5 text-xs font-medium transition-colors ${
                        item.isRequired
                          ? 'bg-red-50 text-red-700 hover:bg-red-100'
                          : 'bg-muted text-muted-foreground hover:bg-muted'
                      }`}
                      data-testid={`checklist-required-toggle-${item.id}`}
                    >
                      {item.isRequired ? tChecklist('itemRequired') : tChecklist('itemOptional')}
                    </button>
                    {!item.isDefault && (
                      <button
                        type="button"
                        onClick={() => void handleRemoveChecklistItem(item.id)}
                        className="text-xs text-red-500 hover:text-red-700"
                        data-testid={`checklist-remove-${item.id}`}
                        aria-label={`Remove ${item.label}`}
                      >
                        ×
                      </button>
                    )}
                  </div>
                </div>
              ))}
            </div>
            {/* Add custom item */}
            <div className="mt-3 flex gap-2">
              <input
                type="text"
                value={newChecklistLabel}
                onChange={(e) => setNewChecklistLabel(e.target.value)}
                placeholder={tChecklist('addItemLabel')}
                className="flex-1 rounded border border-border px-2 py-1 text-sm"
                data-testid="new-checklist-item-input"
              />
              <button
                type="button"
                onClick={() => void handleAddChecklistItem()}
                disabled={!newChecklistLabel.trim()}
                className="rounded bg-blue-600 px-3 py-1 text-sm text-white disabled:opacity-40 hover:bg-blue-700 transition-colors"
                data-testid="add-checklist-item-button"
              >
                +
              </button>
            </div>
          </div>
        )}

        {/* Critical Value Thresholds Config — Story 43.7 (AC #4) — lab_manager only */}
        {isManager && (
          <div
            className="rounded-lg border border-border bg-card p-4"
            data-testid="critical-value-thresholds-settings"
          >
            <h2 className="text-sm font-semibold text-muted-foreground mb-1">
              {tChecklist('thresholdsTitle')}
            </h2>
            <p className="text-xs text-muted-foreground mb-3">{tChecklist('thresholdsDescription')}</p>
            <div className="space-y-2 text-sm">
              <div className="grid grid-cols-5 gap-2 text-xs font-medium text-muted-foreground">
                <span className="col-span-2">{tChecklist('analyteName')}</span>
                <span>{tChecklist('criticalLow')}</span>
                <span>{tChecklist('criticalHigh')}</span>
                <span>{tChecklist('unit')}</span>
              </div>
              {thresholds.map((threshold) => (
                <ThresholdRow
                  key={threshold.loincCode}
                  threshold={threshold}
                  onSave={(t) => void handleSaveThreshold(t)}
                />
              ))}
            </div>
          </div>
        )}

        {/* Daily Report Settings — Story 50.4 */}
        <div className="rounded-lg border border-border bg-card p-4">
          <h2 className="text-sm font-semibold text-muted-foreground mb-3">{tDaily('autoTrigger')}</h2>
          <div className="space-y-3">
            <div>
              <label htmlFor="daily-trigger-time" className="block text-sm text-muted-foreground mb-1">
                {tDaily('triggerTime')}
              </label>
              <input
                id="daily-trigger-time"
                type="time"
                value={dailySettings.autoTriggerTime}
                onChange={(e) => void handleDailySettingChange('autoTriggerTime', e.target.value)}
                className="block w-full rounded-md border border-border bg-card px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div>
              <label htmlFor="daily-facility" className="block text-sm text-muted-foreground mb-1">
                {tDaily('labBranding')}
              </label>
              <input
                id="daily-facility"
                type="text"
                value={dailySettings.facilityName}
                onChange={(e) => void handleDailySettingChange('facilityName', e.target.value)}
                className="block w-full rounded-md border border-border bg-card px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div>
              <label htmlFor="daily-watermark" className="block text-sm text-muted-foreground mb-1">
                {tDaily('watermark')}
              </label>
              <input
                id="daily-watermark"
                type="text"
                value={dailySettings.watermarkText}
                onChange={(e) => void handleDailySettingChange('watermarkText', e.target.value)}
                className="block w-full rounded-md border border-border bg-card px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div>
              <label htmlFor="daily-logo" className="block text-sm text-muted-foreground mb-1">
                {tDaily('logoUpload')}
              </label>
              <input
                id="daily-logo"
                type="file"
                accept="image/png"
                onChange={async (e) => {
                  const file = e.target.files?.[0]
                  if (!file) return
                  if (file.size > 102400) return // max 100KB
                  void handleDailySettingChange('logoBlob', file)
                }}
                className="block w-full text-sm text-muted-foreground file:mr-4 file:rounded file:border-0 file:bg-blue-50 file:px-3 file:py-1.5 file:text-sm file:font-medium file:text-blue-700 hover:file:bg-blue-100"
              />
            </div>
          </div>
        </div>

        {/* SMS Gateway Config — Story 49.2 AC #9: SMS provider settings, lab_manager only */}
        {isManager && <SmsGatewayConfig isManager={isManager} />}

        {/* Surveillance Config — Story 50.3: Reportable disease thresholds, lab_manager only */}
        {isManager && <SurveillanceConfigCard />}

        {/* Security Alert — lab_manager only (Story 49.4) */}
        {isManager && (
          <button
            type="button"
            data-testid="security-alert-button"
            onClick={() => setShowSecurityAlert(true)}
            className="
              w-full rounded-lg border-2 border-red-500 bg-red-50 p-4
              flex items-center gap-3
              hover:bg-red-100 transition-colors
              focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2
              focus-visible:outline-red-600
            "
          >
            <span className="text-2xl" aria-hidden="true">⚠️</span>
            <div className="text-start">
              <p className="text-sm font-bold text-red-800">{tSecurity('settings.button')}</p>
              <p className="text-xs text-red-600 mt-0.5">{tSecurity('settings.buttonDescription')}</p>
            </div>
          </button>
        )}

        {/* AI Behavior — Confidence Inversion Principle (Story 53.5, AC #5) */}
        <div className="rounded-lg border border-border bg-card p-4">
          <h2 className="text-sm font-semibold text-muted-foreground mb-3">{t('aiBehavior')}</h2>
          <ConfidencePrincipleInfo variant="panel" />
        </div>

        {/* Team Quality Achievements — Story 51.7 */}
        <div className="rounded-lg border border-border bg-card p-4" data-testid="gamification-settings">
          <h2 className="text-sm font-semibold text-muted-foreground mb-3">Team Quality Achievements</h2>
          <div className="space-y-3">
            {/* Lab-manager toggle: enable/disable for the whole lab */}
            {isManager && (
              <div className="flex items-center justify-between gap-4">
                <label
                  htmlFor="gamification-enabled"
                  className="text-sm text-foreground"
                >
                  Enable Team Quality Achievements
                </label>
                <button
                  id="gamification-enabled"
                  type="button"
                  role="switch"
                  aria-checked={gamificationEnabled}
                  data-testid="gamification-toggle"
                  onClick={() => void handleGamificationToggle(!gamificationEnabled)}
                  className={`relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 ${
                    gamificationEnabled ? 'bg-blue-600' : 'bg-muted'
                  }`}
                >
                  <span
                    className={`pointer-events-none inline-block h-5 w-5 rounded-full bg-card shadow ring-0 transition-transform ${
                      gamificationEnabled ? 'translate-x-5' : 'translate-x-0'
                    }`}
                  />
                </button>
              </div>
            )}

            {/* Per-tech toggle: show my achievements on team dashboard */}
            {gamificationEnabled && (
              <div className="flex items-center justify-between gap-4">
                <label
                  htmlFor="show-on-dashboard"
                  className="text-sm text-foreground"
                >
                  Show my achievements on team dashboard
                </label>
                <button
                  id="show-on-dashboard"
                  type="button"
                  role="switch"
                  aria-checked={showOnTeamDashboard}
                  data-testid="show-on-dashboard-toggle"
                  onClick={() => void handleShowOnDashboardToggle(!showOnTeamDashboard)}
                  className={`relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 ${
                    showOnTeamDashboard ? 'bg-blue-600' : 'bg-muted'
                  }`}
                >
                  <span
                    className={`pointer-events-none inline-block h-5 w-5 rounded-full bg-card shadow ring-0 transition-transform ${
                      showOnTeamDashboard ? 'translate-x-5' : 'translate-x-0'
                    }`}
                  />
                </button>
              </div>
            )}

            {!gamificationEnabled && !isManager && (
              <p className="text-xs text-muted-foreground">
                Team achievements are not currently enabled for this lab.
              </p>
            )}
          </div>
        </div>

        {/* Donor Program Registration — lab_manager only (Story 50.2) */}
        {isManager && (
          <div className="rounded-lg border border-border bg-card p-4">
            <ProgramRegistration />
          </div>
        )}

        {/* Sign Out */}
        <Button
          variant="danger"
          fullWidth
          type="button"
          onClick={handleSignOut}
        >
          {t('signOut')}
        </Button>
      </div>

      {/* Security Alert Flow — full-screen overlay */}
      {showSecurityAlert && (
        <SecurityAlertFlow onClose={() => setShowSecurityAlert(false)} />
      )}
    </div>
  )
}

// ---------------------------------------------------------------------------
// ThresholdRow — inline editable row for a single critical value threshold
// Story 43.7 AC #4 (configurable thresholds per lab)
// ---------------------------------------------------------------------------

interface ThresholdRowProps {
  threshold: CriticalValueThreshold
  onSave: (threshold: CriticalValueThreshold) => void
}

function ThresholdRow({ threshold, onSave }: ThresholdRowProps) {
  const [low, setLow] = useState<string>(
    threshold.criticalLow != null ? String(threshold.criticalLow) : '',
  )
  const [high, setHigh] = useState<string>(
    threshold.criticalHigh != null ? String(threshold.criticalHigh) : '',
  )
  const [dirty, setDirty] = useState(false)

  function handleChange(field: 'low' | 'high', value: string) {
    if (field === 'low') setLow(value)
    else setHigh(value)
    setDirty(true)
  }

  function handleSave() {
    onSave({
      ...threshold,
      criticalLow: low !== '' ? parseFloat(low) : null,
      criticalHigh: high !== '' ? parseFloat(high) : null,
    })
    setDirty(false)
  }

  return (
    <div className="grid grid-cols-5 gap-2 items-center text-sm">
      <span className="col-span-2 text-foreground">{threshold.analyte}</span>
      <input
        type="number"
        value={low}
        onChange={(e) => handleChange('low', e.target.value)}
        className="rounded border border-border px-1 py-0.5 text-sm text-end w-full"
        data-testid={`threshold-low-${threshold.loincCode}`}
        placeholder="—"
      />
      <input
        type="number"
        value={high}
        onChange={(e) => handleChange('high', e.target.value)}
        className="rounded border border-border px-1 py-0.5 text-sm text-end w-full"
        data-testid={`threshold-high-${threshold.loincCode}`}
        placeholder="—"
      />
      <div className="flex items-center gap-1">
        <span className="text-xs text-muted-foreground truncate">{threshold.unit}</span>
        {dirty && (
          <button
            type="button"
            onClick={handleSave}
            className="ms-1 rounded bg-blue-600 px-1.5 py-0.5 text-xs text-white hover:bg-blue-700"
            data-testid={`threshold-save-${threshold.loincCode}`}
          >
            ✓
          </button>
        )}
      </div>
    </div>
  )
}
