// ---------------------------------------------------------------------------
// Story 50.4 — Daily Activity Log (WhatsApp-Shareable)
// Aggregate-only data model — NO PHI. All fields are de-identified counts/stats.
// ---------------------------------------------------------------------------

export interface TestTypeSummary {
  loincCode: string
  testLabel: string
  totalPerformed: number
  totalPositive: number
  totalNegative: number
}

export interface WorkflowMetrics {
  samplesReceived: number
  samplesCompleted: number
  samplesPending: number
  completionRate: number // Percentage (0-100)
}

export interface TurnaroundTimeStats {
  minHours: number
  avgHours: number
  maxHours: number
  sampleCount: number // Number of samples used for TAT calculation
}

export interface RejectionReason {
  reason: string // e.g., 'hemolyzed', 'clotted', 'insufficient', 'mislabeled'
  count: number
}

export interface RejectionSummary {
  totalRejected: number
  reasons: RejectionReason[]
}

export interface EquipmentStatusEntry {
  equipmentName: string
  status: 'operational' | 'maintenance' | 'offline'
  notes?: string
}

export interface DailyActivityLog {
  id: string // UUID v4
  logDate: string // ISO 8601 date (YYYY-MM-DD)
  facilityName: string // Lab name from settings
  generatedAt: string // ISO 8601 timestamp
  generatedBy: string // Practitioner ID

  testSummary: TestTypeSummary[]
  workflowMetrics: WorkflowMetrics
  turnaroundTime: TurnaroundTimeStats
  rejections: RejectionSummary
  stockoutAlerts: string[] // List of reagents/supplies at zero stock
  equipmentStatus: EquipmentStatusEntry[]

  imageBlob?: Blob // The rendered PNG (stored in Dexie)
  imageHash: string // SHA-256 hash of the image data (first 8 chars = verification code)
  status: 'generated' | 'shared'
}

/** Settings for daily log auto-trigger and branding — keyed by 'config' (singleton). */
export interface DailyLogSettings {
  id: 'config'
  autoTriggerTime: string // HH:mm 24h format, default "17:00"
  lastAutoGenerateDate: string // ISO date — prevents duplicate auto-generation
  facilityName: string // branding name shown in image header
  watermarkText: string // diagonal watermark text
  logoBlob?: Blob // optional lab logo PNG (max 100KB)
}
