// ---------------------------------------------------------------------------
// Story 50.4 — Daily Activity Log End-of-Day Scheduler
// Lightweight interval-based scheduler. Checks every 5 minutes whether the
// configured auto-trigger time has passed. Generates the daily log once per
// day (duplicate prevention via lastAutoGenerateDate in Dexie).
// NEVER auto-shares — always requires manual review and explicit share action.
// ---------------------------------------------------------------------------

import { getDailyLogSettings, saveDailyLogSettings, saveDailyLog, getDailyLogByDate } from './db'
import { aggregateDailyData } from './daily-log-aggregator'
import { computeLogHash } from './daily-log-image'
import type { DailyActivityLog } from './daily-log-types'

const CHECK_INTERVAL_MS = 5 * 60 * 1000 // 5 minutes

let intervalId: ReturnType<typeof setInterval> | null = null
let onReadyCallback: ((log: DailyActivityLog) => void) | null = null

function todayISO(): string {
  return new Date().toISOString().slice(0, 10)
}

/** Returns true if current local time is at or past HH:mm. */
function isPastTriggerTime(triggerTime: string): boolean {
  const [hStr, mStr] = triggerTime.split(':')
  const h = parseInt(hStr ?? '17', 10)
  const m = parseInt(mStr ?? '0', 10)
  const now = new Date()
  return now.getHours() > h || (now.getHours() === h && now.getMinutes() >= m)
}

async function checkAndGenerate(practitionerId: string, facilityName: string): Promise<void> {
  try {
    const settings = await getDailyLogSettings()
    const today = todayISO()

    // Already generated today — skip
    if (settings.lastAutoGenerateDate === today) return

    // Not past trigger time yet — skip
    if (!isPastTriggerTime(settings.autoTriggerTime)) return

    // Check if a log for today already exists in Dexie (manual generation may have run first)
    const existing = await getDailyLogByDate(today)
    if (existing) {
      // Update lastAutoGenerateDate to prevent future duplicate triggers
      await saveDailyLogSettings({ ...settings, lastAutoGenerateDate: today })
      return
    }

    // Generate the daily log
    const partial = await aggregateDailyData(today, practitionerId, facilityName)
    const hash = await computeLogHash(partial)
    const log: DailyActivityLog = {
      ...partial,
      id: crypto.randomUUID(),
      imageHash: hash,
      status: 'generated',
      // imageBlob intentionally omitted from auto-generation — tech must open the page to render
    }

    await saveDailyLog(log)
    await saveDailyLogSettings({ ...settings, lastAutoGenerateDate: today })

    // Notify the app (e.g. show in-app notification banner)
    if (onReadyCallback) {
      onReadyCallback(log)
    }
  } catch {
    // Scheduler must never throw — silently skip on error
  }
}

/**
 * Start the end-of-day scheduler.
 * @param practitionerId  The logged-in practitioner ID (opaque — no PHI)
 * @param facilityName    Lab name from settings
 * @param onReady         Callback invoked when a daily log is auto-generated
 */
export function startDailyLogScheduler(
  practitionerId: string,
  facilityName: string,
  onReady?: (log: DailyActivityLog) => void,
): void {
  if (intervalId !== null) return // already running

  onReadyCallback = onReady ?? null

  // Run immediately in case the app opened after the trigger time
  void checkAndGenerate(practitionerId, facilityName)

  intervalId = setInterval(() => {
    void checkAndGenerate(practitionerId, facilityName)
  }, CHECK_INTERVAL_MS)
}

/** Stop the end-of-day scheduler (call on sign-out or unmount). */
export function stopDailyLogScheduler(): void {
  if (intervalId !== null) {
    clearInterval(intervalId)
    intervalId = null
  }
  onReadyCallback = null
}

/** Exported for testing: exposes the check function without the interval (silently catches errors). */
export { checkAndGenerate as _checkAndGenerateForTest }

/**
 * Test-only: same as checkAndGenerate but re-throws on error.
 * Use in unit tests where you need to inspect failures.
 */
export async function _checkAndGenerateDebug(practitionerId: string, facilityName: string): Promise<void> {
  const settings = await getDailyLogSettings()
  const today = todayISO()
  if (settings.lastAutoGenerateDate === today) return
  if (!isPastTriggerTime(settings.autoTriggerTime)) return
  const existing = await getDailyLogByDate(today)
  if (existing) {
    await saveDailyLogSettings({ ...settings, lastAutoGenerateDate: today })
    return
  }
  const partial = await aggregateDailyData(today, practitionerId, facilityName)
  const hash = await computeLogHash(partial)
  const log: DailyActivityLog = {
    ...partial,
    id: crypto.randomUUID(),
    imageHash: hash,
    status: 'generated',
  }
  await saveDailyLog(log)
  await saveDailyLogSettings({ ...settings, lastAutoGenerateDate: today })
  if (onReadyCallback) onReadyCallback(log)
}
