/**
 * Guidance Audio Bundle — AUTO-GENERATED by scripts/prepare-guidance-audio.ts
 *
 * DO NOT EDIT MANUALLY.
 * Re-generate with: pnpm tsx scripts/prepare-guidance-audio.ts
 *
 * Generated: 2026-05-31T00:00:00.000Z (initial placeholder — no recordings yet)
 * Total audio files: 0 / 24
 * Total encoded size: 0 KB
 *
 * Empty strings indicate recordings not yet available.
 * See scripts/prepare-guidance-audio.ts for recording requirements:
 *   - Native speakers, clear pronunciation, measured pace, quiet background
 *   - MP3 mono 64kbps, ≤ 500 KB per file (≤ 60s of speech)
 *   - Naming: CONDITION_CODE-locale.mp3
 *     e.g. MALARIA_POSITIVE-en.mp3, TB_POSITIVE-prs.mp3
 */

/**
 * Pre-encoded base64 audio for each guidance condition in all four languages.
 * Audio files are MP3 mono 64kbps, encoded as base64 for offline bundling.
 * Empty string = recording not yet provided → UI hides the audio button.
 */
export const GUIDANCE_AUDIO_BUNDLE: Record<string, { en: string; ar: string; prs: string; ps: string }> = {
  "MALARIA_POSITIVE": { "en": "", "ar": "", "prs": "", "ps": "" },
  "TB_POSITIVE": { "en": "", "ar": "", "prs": "", "ps": "" },
  "HEPATITIS_B_POSITIVE": { "en": "", "ar": "", "prs": "", "ps": "" },
  "HEPATITIS_C_POSITIVE": { "en": "", "ar": "", "prs": "", "ps": "" },
  "HIV_POSITIVE": { "en": "", "ar": "", "prs": "", "ps": "" },
  "ANEMIA_SEVERE": { "en": "", "ar": "", "prs": "", "ps": "" }
}
