// ---------------------------------------------------------------------------
// Story 50.1 — HMIS Monthly Report PDF Export
// Generates a PDF matching the Afghan MoPH HMIS template layout.
// Uses jsPDF + jspdf-autotable — runs entirely client-side, works offline.
//
// PHI safety: HMIS report contains only aggregate statistics — NO PHI.
// No patient names, IDs, diagnoses, or individual-level data in the output.
// ---------------------------------------------------------------------------

import type { HmisMonthlyReport } from './hmis-types'
import { formatReportingPeriod, HMIS_SECTIONS } from './hmis-template'

const RTL_LOCALES = ['ar', 'prs', 'ps']

/**
 * Generate a PDF Blob for the HMIS monthly report.
 * Returns a Blob that can be used to create an object URL for download.
 */
export async function exportHmisPdf(
  report: HmisMonthlyReport,
  locale: string,
): Promise<Blob> {
  const { default: jsPDF } = await import('jspdf')
  const { default: autoTable } = await import('jspdf-autotable')

  const isRtl = RTL_LOCALES.includes(locale)
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', putOnlyUsedFonts: true })
  const pageWidth = doc.internal.pageSize.width
  const startX = isRtl ? pageWidth - 14 : 14
  const align = isRtl ? 'right' : 'left'
  const period = formatReportingPeriod(report.reportYear, report.reportMonth)

  // PDF metadata
  doc.setProperties({
    title: `HMIS Monthly Report — ${period}`,
    author: report.facilityName,
    subject: 'Afghan MoPH HMIS Laboratory Report',
    creator: 'Lab Lite — Ultranos',
  })

  // ---------------------------------------------------------------------------
  // Header
  // ---------------------------------------------------------------------------
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('HMIS Monthly Laboratory Report', startX, 18, { align })

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(`${report.facilityName} — ${report.facilityProvince}, ${report.facilityDistrict}`, startX, 25, { align })
  doc.text(`Reporting Period: ${period}`, startX, 31, { align })
  doc.text(
    `Status: ${report.status === 'finalized' ? 'Finalized' : 'Draft'}`,
    isRtl ? 14 : pageWidth - 14,
    31,
    { align: isRtl ? 'left' : 'right' },
  )

  let cursorY = 38

  // ---------------------------------------------------------------------------
  // Section A: Facility Information
  // ---------------------------------------------------------------------------
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('Section A — Facility Information', startX, cursorY, { align })
  cursorY += 2

  autoTable(doc, {
    startY: cursorY,
    head: [['Field', 'Value']],
    body: [
      ['Facility Name', report.facilityName],
      ['Province', report.facilityProvince || '—'],
      ['District', report.facilityDistrict || '—'],
      ['Reporting Period', period],
      ['Generated By', report.generatedBy],
      ['Generated At', new Date(report.generatedAt).toLocaleString()],
    ],
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
    margin: { left: 14, right: 14 },
    theme: 'striped',
  })

  cursorY = (doc as any).lastAutoTable.finalY + 8

  // ---------------------------------------------------------------------------
  // Section B: Test Volume Summary
  // ---------------------------------------------------------------------------
  doc.setFont('helvetica', 'bold')
  doc.text('Section B — Test Volume Summary', startX, cursorY, { align })
  cursorY += 2

  const bBody = report.testCategorySummary.length > 0
    ? report.testCategorySummary.map((cat) => [
        cat.categoryLabel,
        String(cat.totalPerformed),
        String(cat.totalPositive),
        String(cat.totalNegative),
        `${cat.positivityRate}%`,
      ])
    : [['No data for this period', '', '', '', '']]

  autoTable(doc, {
    startY: cursorY,
    head: [['Test Category', 'Total', 'Positive', 'Negative', 'Rate %']],
    body: bBody,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
    margin: { left: 14, right: 14 },
    theme: 'striped',
  })

  cursorY = (doc as any).lastAutoTable.finalY + 8

  // ---------------------------------------------------------------------------
  // Section C: Reportable Disease Surveillance
  // ---------------------------------------------------------------------------
  doc.setFont('helvetica', 'bold')
  doc.text('Section C — Reportable Disease Surveillance', startX, cursorY, { align })
  cursorY += 2

  autoTable(doc, {
    startY: cursorY,
    head: [['Disease', 'Total Tested', 'Total Positive', 'Rate %', 'Previous Month']],
    body: report.positivityRates.map((d) => [
      d.diseaseLabel,
      String(d.totalTested),
      String(d.totalPositive),
      `${d.positivityRate}%`,
      d.previousMonthRate != null ? `${d.previousMonthRate}%` : '—',
    ]),
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
    margin: { left: 14, right: 14 },
    theme: 'striped',
  })

  cursorY = (doc as any).lastAutoTable.finalY + 8

  // Add new page if needed
  if (cursorY > 250) {
    doc.addPage()
    cursorY = 20
  }

  // ---------------------------------------------------------------------------
  // Section D: Demographic Distribution
  // ---------------------------------------------------------------------------
  doc.setFont('helvetica', 'bold')
  doc.text('Section D — Demographic Distribution', startX, cursorY, { align })
  cursorY += 2

  autoTable(doc, {
    startY: cursorY,
    head: [['Age Group', 'Male', 'Female', 'Unknown', 'Total']],
    body: report.demographics.map((d) => [
      d.ageGroup,
      String(d.male),
      String(d.female),
      String(d.unknown),
      String(d.total),
    ]),
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
    margin: { left: 14, right: 14 },
    theme: 'striped',
  })

  cursorY = (doc as any).lastAutoTable.finalY + 8

  // ---------------------------------------------------------------------------
  // Section E: Reagent Consumption
  // ---------------------------------------------------------------------------
  doc.setFont('helvetica', 'bold')
  doc.text('Section E — Reagent & Supply Consumption', startX, cursorY, { align })
  cursorY += 2

  const eBody = report.reagentConsumption.length > 0
    ? report.reagentConsumption.map((r) => [
        r.reagentName,
        String(r.unitsConsumed),
        String(r.unitsRemaining),
        String(r.estimatedDaysRemaining),
      ])
    : [['No reagent data — manual entry required', '', '', '']]

  autoTable(doc, {
    startY: cursorY,
    head: [['Reagent', 'Consumed', 'Remaining', 'Est. Days']],
    body: eBody,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
    margin: { left: 14, right: 14 },
    theme: 'striped',
  })

  cursorY = (doc as any).lastAutoTable.finalY + 8

  // ---------------------------------------------------------------------------
  // Section F: Quality Indicators
  // ---------------------------------------------------------------------------
  doc.setFont('helvetica', 'bold')
  doc.text('Section F — Quality Indicators', startX, cursorY, { align })
  cursorY += 2

  const qi = report.qualityIndicators
  autoTable(doc, {
    startY: cursorY,
    head: [['Indicator', 'Value']],
    body: [
      ['Total Samples Received', String(qi.totalSamplesReceived)],
      ['Rejected Samples', String(qi.rejectedSamples)],
      ['Rejection Rate', `${qi.rejectionRate}%`],
      ['QC Pass Rate', `${qi.qcPassRate}%`],
      ['Average TAT (hours)', String(qi.averageTatHours)],
    ],
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
    margin: { left: 14, right: 14 },
    theme: 'striped',
  })

  cursorY = (doc as any).lastAutoTable.finalY + 12

  // Add new page for footer if needed
  if (cursorY > 260) {
    doc.addPage()
    cursorY = 20
  }

  // ---------------------------------------------------------------------------
  // Footer: Certification block
  // ---------------------------------------------------------------------------
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.text('Certification', startX, cursorY, { align })
  cursorY += 6

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)

  const lineY1 = cursorY + 8
  const lineY2 = cursorY + 8
  const colLeft = 14
  const colRight = pageWidth / 2 + 10

  // Prepared by
  doc.text('Prepared by:', colLeft, cursorY)
  doc.text('Reviewed by:', colRight, cursorY)
  doc.line(colLeft, lineY1, colLeft + 60, lineY1)
  doc.line(colRight, lineY2, colRight + 60, lineY2)
  cursorY += 14

  // Date
  doc.text('Date:', colLeft, cursorY)
  doc.text('Date:', colRight, cursorY)
  doc.line(colLeft + 10, cursorY, colLeft + 60, cursorY)
  doc.line(colRight + 10, cursorY, colRight + 60, cursorY)

  // Corrections note
  if (report.corrections.length > 0) {
    cursorY += 10
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.text(
      `Note: ${report.corrections.length} field(s) were manually corrected during review.`,
      startX,
      cursorY,
      { align },
    )
  }

  return doc.output('blob')
}
