/**
 * Logbook PDF Export — Story 42.8
 *
 * Generates a PDF matching the Afghan MoPH paper register layout.
 * Uses jsPDF + jspdf-autotable — runs entirely client-side, works offline.
 *
 * PHI safety: PDF export is a PHI operation — audit event must be emitted
 * BEFORE calling this function (handled in the page component).
 */

import type { LabLogbookEntry } from './db'

export interface LogbookPdfFilters {
  dateFrom?: string
  dateTo?: string
  testType?: string
  technicianId?: string
}

const RTL_LOCALES = ['ar', 'prs', 'ps']

/**
 * Generate a PDF Blob matching the MoPH laboratory register format.
 * Returns a Blob that can be used to create an object URL for download.
 *
 * PDF content includes PHI (patient names, results) — handle with care.
 * Never log the resulting blob or pass its contents to error messages.
 */
export async function exportLogbookPdf(
  entries: LabLogbookEntry[],
  filters: LogbookPdfFilters,
  facilityName: string,
  locale: string,
): Promise<Blob> {
  const { default: jsPDF } = await import('jspdf')
  const { default: autoTable } = await import('jspdf-autotable')

  const isRtl = RTL_LOCALES.includes(locale)
  const doc = new jsPDF({ orientation: 'landscape', putOnlyUsedFonts: true })
  const pageWidth = doc.internal.pageSize.width
  const startX = isRtl ? pageWidth - 14 : 14

  // Header
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(facilityName, startX, 15, { align: isRtl ? 'right' : 'left' })

  doc.setFontSize(12)
  doc.text('Laboratory Register', startX, 22, { align: isRtl ? 'right' : 'left' })

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  const dateRangeParts: string[] = []
  if (filters.dateFrom) dateRangeParts.push(`From: ${filters.dateFrom}`)
  if (filters.dateTo) dateRangeParts.push(`To: ${filters.dateTo}`)
  if (dateRangeParts.length > 0) {
    doc.text(dateRangeParts.join('  '), startX, 28, { align: isRtl ? 'right' : 'left' })
  }
  const exportTimestamp = `Exported: ${new Date().toLocaleString()}`
  doc.text(exportTimestamp, startX, 34, { align: isRtl ? 'right' : 'left' })

  // Table — columns matching MoPH paper register
  autoTable(doc, {
    head: [
      ['#', 'Date', 'Patient', 'Age', 'Test', 'Result', 'Technician', 'Auth. By', 'Status', 'Remarks'],
    ],
    body: entries.map((e) => [
      e.displayNumber,
      new Date(e.date).toLocaleDateString(),
      `${e.patientFirstName} (${e.patientRef})`,
      String(e.patientAge),
      e.testType,
      e.resultSummary,
      e.technicianName,
      e.authorizerName,
      e.authorizationStatus,
      e.amendmentReason ?? '',
    ]),
    startY: 38,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      5: { cellWidth: 40 }, // Result column — wider
    },
  })

  // Footer on each page
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    const pageHeight = doc.internal.pageSize.height
    doc.text(`Page ${i} of ${pageCount}`, 14, pageHeight - 10)
    doc.text('Generated by Ultranos Lab Lite', pageWidth - 14, pageHeight - 10, { align: 'right' })
  }

  return doc.output('blob')
}
