/**
 * portfolio-export.ts — Story 51.6 / 51.7
 *
 * Generates an HTML portfolio export for a technician, including
 * achievement badges (Story 51.7 AC 4).
 * No PHI in the output — tech IDs and operational metrics only.
 */

import type { PortfolioMetrics } from './portfolio-service'
import { AchievementType } from './db'

const ACHIEVEMENT_ICONS: Record<AchievementType, string> = {
  [AchievementType.QC_CHAMPION]: '🏆',
  [AchievementType.ZERO_REJECTION_WEEK]: '✨',
  [AchievementType.SPEED_STAR]: '⚡',
  [AchievementType.CONSISTENCY_AWARD]: '🎯',
  [AchievementType.MENTORSHIP_BADGE]: '🤝',
  [AchievementType.TEAM_MILESTONE_1K]: '🌟',
  [AchievementType.TEAM_MILESTONE_5K]: '🌟',
  [AchievementType.TEAM_MILESTONE_10K]: '🌟',
}

const ACHIEVEMENT_NAMES: Record<AchievementType, string> = {
  [AchievementType.QC_CHAMPION]: 'QC Champion',
  [AchievementType.ZERO_REJECTION_WEEK]: 'Zero Rejection Week',
  [AchievementType.SPEED_STAR]: 'Speed Star',
  [AchievementType.CONSISTENCY_AWARD]: 'Consistency Award',
  [AchievementType.MENTORSHIP_BADGE]: 'Mentorship Badge',
  [AchievementType.TEAM_MILESTONE_1K]: 'Team Milestone: 1,000 Tests',
  [AchievementType.TEAM_MILESTONE_5K]: 'Team Milestone: 5,000 Tests',
  [AchievementType.TEAM_MILESTONE_10K]: 'Team Milestone: 10,000 Tests',
}

/**
 * Generate a self-contained HTML string for a portfolio export.
 */
export function generatePortfolioHtml(
  metrics: PortfolioMetrics,
  techName: string,
): string {
  const generatedAt = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  const achievementsHtml =
    metrics.achievements.length === 0
      ? '<p style="color:#6b7280;font-style:italic">No achievements earned yet.</p>'
      : metrics.achievements
          .sort((a, b) => b.earnedAt.localeCompare(a.earnedAt))
          .map((a) => {
            const icon = ACHIEVEMENT_ICONS[a.type] ?? '⭐'
            const name = ACHIEVEMENT_NAMES[a.type] ?? a.type
            const date = new Date(a.earnedAt).toLocaleDateString()
            return `
        <div style="display:flex;align-items:flex-start;gap:12px;padding:12px;border:1px solid #e5e7eb;border-radius:8px;margin-bottom:8px">
          <span style="font-size:24px">${icon}</span>
          <div>
            <p style="margin:0;font-weight:600;font-size:14px">${name}</p>
            <p style="margin:4px 0 0;font-size:12px;color:#6b7280">${a.description}</p>
            <p style="margin:4px 0 0;font-size:11px;color:#9ca3af">Earned: ${date}</p>
          </div>
        </div>`
          })
          .join('')

  const qcDisplay =
    metrics.qcPassRate !== null
      ? `${Math.round(metrics.qcPassRate * 100)}%`
      : 'N/A'

  const tatDisplay =
    metrics.avgTatMinutes !== null
      ? `${Math.round(metrics.avgTatMinutes)} min avg`
      : 'N/A'

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Performance Portfolio — ${techName}</title>
  <style>
    body { font-family: sans-serif; max-width: 800px; margin: 0 auto; padding: 24px; color: #111827; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .subtitle { color: #6b7280; font-size: 14px; margin-bottom: 24px; }
    .section { margin-bottom: 32px; }
    .section h2 { font-size: 16px; font-weight: 600; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; margin-bottom: 16px; }
    .stat-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; }
    .stat-card { padding: 12px; border: 1px solid #e5e7eb; border-radius: 8px; }
    .stat-value { font-size: 24px; font-weight: 700; color: #1d4ed8; }
    .stat-label { font-size: 12px; color: #6b7280; margin-top: 2px; }
    .footer { margin-top: 40px; font-size: 11px; color: #9ca3af; }
  </style>
</head>
<body>
  <h1>Performance Portfolio</h1>
  <p class="subtitle">${techName} · Generated ${generatedAt}</p>

  <div class="section">
    <h2>Performance Summary</h2>
    <div class="stat-grid">
      <div class="stat-card">
        <div class="stat-value">${metrics.completedResultsEntered}</div>
        <div class="stat-label">Results Completed</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${qcDisplay}</div>
        <div class="stat-label">QC First-Attempt Pass Rate</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${tatDisplay}</div>
        <div class="stat-label">Average Turnaround Time</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${metrics.mentorshipSessionCount}</div>
        <div class="stat-label">Mentorship Sessions</div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>Achievements (${metrics.achievements.length})</h2>
    ${achievementsHtml}
  </div>

  <div class="footer">
    Generated by Ultranos Lab Lite · ${generatedAt}
  </div>
</body>
</html>`
}

/**
 * Trigger a browser download of the portfolio HTML.
 */
export function downloadPortfolioHtml(html: string, techName: string): void {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `portfolio-${techName.replace(/\s+/g, '-').toLowerCase()}.html`
  a.click()
  URL.revokeObjectURL(url)
}
