/**
 * Sitrep PDF Generation — Story 54.5 (AC #7, Task 11)
 *
 * Generates a PDF blob for a daily sitrep.
 * No patient-level PHI — lab identification and aggregate metrics only (AC #11.3).
 *
 * Implementation: pure HTML-to-PDF via window.print() or Blob of HTML text
 * (no external PDF library required — avoids adding new dependencies).
 * The Blob is a text/html document that the browser can print to PDF.
 *
 * For environments where a PDF library (e.g. jsPDF) is available, this module
 * can be extended; the interface remains the same.
 */

import type { DailySitrep, OutbreakModeConfig } from '@/types/outbreak'

/**
 * Render a sitrep as a PDF-ready HTML Blob.
 * Returns a Blob of type 'text/html' suitable for download and browser-print-to-PDF.
 * No PHI included — lab name, pathogen code, aggregate metrics only.
 */
export function renderSitrepPDF(
  sitrep: DailySitrep,
  outbreakConfig: OutbreakModeConfig,
): Blob {
  const stockoutDisplay = sitrep.projectedStockoutDate
    ? sitrep.projectedStockoutDate
    : '> 30 days'

  const stockoutStyle = sitrep.projectedStockoutDate
    ? (() => {
        const days = Math.floor(
          (new Date(sitrep.projectedStockoutDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24),
        )
        return days < 7 ? 'color:#dc2626;font-weight:700' : days < 14 ? 'color:#d97706;font-weight:700' : 'color:#16a34a'
      })()
    : 'color:#16a34a'

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Sitrep ${sitrep.reportDate} — ${outbreakConfig.targetPathogen.display}</title>
<style>
  body { font-family: Arial, sans-serif; margin: 2cm; color: #111; }
  h1 { font-size: 1.4rem; color: #dc2626; border-bottom: 2px solid #dc2626; padding-bottom: 0.5rem; }
  h2 { font-size: 1rem; margin-top: 1.5rem; }
  table { width: 100%; border-collapse: collapse; margin-top: 0.5rem; }
  th { background: #f9fafb; text-align: left; padding: 0.5rem; font-size: 0.8rem; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; border: 1px solid #e5e7eb; }
  td { padding: 0.5rem; border: 1px solid #e5e7eb; }
  .metric-value { font-size: 1.5rem; font-weight: 700; }
  .positive { color: #dc2626; }
  footer { margin-top: 2rem; font-size: 0.75rem; color: #9ca3af; }
  @media print { body { margin: 1.5cm; } }
</style>
</head>
<body>
<h1>OUTBREAK SITUATION REPORT</h1>
<table>
  <tr><th>Pathogen</th><td>${escapeHtml(outbreakConfig.targetPathogen.display)}</td></tr>
  <tr><th>Report Date</th><td>${escapeHtml(sitrep.reportDate)}</td></tr>
  <tr><th>Outbreak Config ID</th><td>${escapeHtml(outbreakConfig.id)}</td></tr>
  <tr><th>Generated At</th><td>${escapeHtml(sitrep.generatedAt)}</td></tr>
  <tr><th>Generated By</th><td>${escapeHtml(sitrep.generatedBy)}</td></tr>
</table>

<h2>Daily Metrics</h2>
<table>
  <tr>
    <th>Metric</th>
    <th>Value</th>
  </tr>
  <tr>
    <td>Total Tests Performed</td>
    <td class="metric-value">${sitrep.totalTestsPerformed}</td>
  </tr>
  <tr>
    <td>Positive Count</td>
    <td class="metric-value positive">${sitrep.positiveCount}</td>
  </tr>
  <tr>
    <td>Positivity Rate</td>
    <td class="metric-value">${sitrep.positivityRate}%</td>
  </tr>
  <tr>
    <td>Reagent Burn Rate</td>
    <td class="metric-value">${sitrep.reagentBurnRate} units/day</td>
  </tr>
  <tr>
    <td>Pending Samples</td>
    <td>${sitrep.pendingSamples}</td>
  </tr>
  <tr>
    <td>Projected Stockout Date</td>
    <td style="${stockoutStyle}">${escapeHtml(stockoutDisplay)}</td>
  </tr>
</table>

<footer>
  <p>CONFIDENTIAL — Aggregate operational data only. No patient identifiers included.</p>
  <p>Ultranos Lab-Lite | Report ID: ${escapeHtml(sitrep.id)}</p>
</footer>
</body>
</html>`

  return new Blob([html], { type: 'text/html;charset=utf-8' })
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}
