import type { AfghanProvince } from './afghanistan-geo.js'

export interface AfghanDistrict {
  /** English canonical name (ALA-LC romanized) */
  name: string
  /** Dari/Pashto script name */
  nameLocal: string
  /** Parent province */
  province: AfghanProvince
}

// Source: Afghanistan Central Statistics Organization (CSO) district list.
// English names from CSO English publication; Dari names from CSO Dari publication.
// Reviewed against: "Afghanistan Provinces and Districts (English)" and
// "Afghanistan Provinces and Districts (Dari)" reference PDFs.
export const AFGHAN_DISTRICTS: readonly AfghanDistrict[] = [
  // Badakhshan Province (28 districts)
  { name: 'Arghanj Khwa',    nameLocal: 'ارغنجخواه',      province: 'Badakhshan' },
  { name: 'Argo',            nameLocal: 'ارگو',            province: 'Badakhshan' },
  { name: 'Baharak',         nameLocal: 'بهارک',           province: 'Badakhshan' },
  { name: 'Darayim',         nameLocal: 'درايم',           province: 'Badakhshan' },
  { name: 'Fayzabad',        nameLocal: 'فيض آباد',        province: 'Badakhshan' },
  { name: 'Ishkashim',       nameLocal: 'اشکاشم',          province: 'Badakhshan' },
  { name: 'Jurm',            nameLocal: 'جرم',             province: 'Badakhshan' },
  { name: 'Khash',           nameLocal: 'خاش',             province: 'Badakhshan' },
  { name: 'Khwahan',         nameLocal: 'خواهان',          province: 'Badakhshan' },
  { name: 'Kishim',          nameLocal: 'کشيم',            province: 'Badakhshan' },
  { name: 'Kohistan',        nameLocal: 'کوهستان',         province: 'Badakhshan' },
  { name: 'Kuf Ab',          nameLocal: 'کوف آب',          province: 'Badakhshan' },
  { name: 'Keran wa Menjan', nameLocal: 'کوران و منجان',   province: 'Badakhshan' },
  { name: 'Maimay',          nameLocal: 'مايمی',           province: 'Badakhshan' },
  { name: 'Nusay',           nameLocal: 'نسی',             province: 'Badakhshan' },
  { name: 'Raghistan',       nameLocal: 'راغستان',         province: 'Badakhshan' },
  { name: 'Shahri Buzurg',   nameLocal: 'شهر بزرگ',        province: 'Badakhshan' },
  { name: 'Sheghnan',        nameLocal: 'شغنان',           province: 'Badakhshan' },
  { name: 'Shekay',          nameLocal: 'شکی',             province: 'Badakhshan' },
  { name: 'Shuhada',         nameLocal: 'شهدا',            province: 'Badakhshan' },
  { name: 'Tagab',           nameLocal: 'تگاب',            province: 'Badakhshan' },
  { name: 'Tishkan',         nameLocal: 'تيشکان',          province: 'Badakhshan' },
  { name: 'Wakhan',          nameLocal: 'واخان',           province: 'Badakhshan' },
  { name: 'Warduj',          nameLocal: 'وردوج',           province: 'Badakhshan' },
  { name: 'Yaftali Sufla',   nameLocal: 'يفتل پايين',      province: 'Badakhshan' },
  { name: 'Yamgan',          nameLocal: 'يمگان',           province: 'Badakhshan' },
  { name: 'Yawan',           nameLocal: 'ياوان',           province: 'Badakhshan' },
  { name: 'Zebak',           nameLocal: 'زيباک',           province: 'Badakhshan' },

  // Badghis Province (7 districts)
  { name: 'Ab Kamari',       nameLocal: 'آب کمری',         province: 'Badghis' },
  { name: 'Bala Murghab',    nameLocal: 'بالا مرغاب',      province: 'Badghis' },
  { name: 'Ghormach',        nameLocal: 'غورماچ',          province: 'Badghis' },
  { name: 'Jawand',          nameLocal: 'جوند',            province: 'Badghis' },
  { name: 'Muqur',           nameLocal: 'مقر',             province: 'Badghis' },
  { name: 'Qadis',           nameLocal: 'قاديس',           province: 'Badghis' },
  { name: 'Qala-i-Naw',      nameLocal: 'قلعه نو',         province: 'Badghis' },

  // Baghlan Province (15 districts)
  { name: 'Andarab',          nameLocal: 'اندراب',          province: 'Baghlan' },
  { name: 'Baghlani Jadid',   nameLocal: 'بغلان جديد',      province: 'Baghlan' },
  { name: 'Burka',            nameLocal: 'برکه',            province: 'Baghlan' },
  { name: 'Dahana-i-Ghuri',   nameLocal: 'دهانه غوری',      province: 'Baghlan' },
  { name: 'Dih Salah',        nameLocal: 'دهصلاح',          province: 'Baghlan' },
  { name: 'Dushi',            nameLocal: 'دوشی',            province: 'Baghlan' },
  { name: 'Farang wa Gharu',  nameLocal: 'فرنگ و غارو',     province: 'Baghlan' },
  { name: 'Guzargahi Nur',    nameLocal: 'گذرگاه نور',      province: 'Baghlan' },
  { name: 'Khinjan',          nameLocal: 'خنجان',           province: 'Baghlan' },
  { name: 'Khost wa Fereng',  nameLocal: 'خوست و فرنگ',     province: 'Baghlan' },
  { name: 'Khwaja Hijran',    nameLocal: 'خواجه حجران',     province: 'Baghlan' },
  { name: 'Nahrin',           nameLocal: 'نهرين',           province: 'Baghlan' },
  { name: 'Puli Hisar',       nameLocal: 'پل حصار',         province: 'Baghlan' },
  { name: 'Puli Khumri',      nameLocal: 'پل خمری',         province: 'Baghlan' },
  { name: 'Tala wa Barfak',   nameLocal: 'تاله و برفک',     province: 'Baghlan' },

  // Balkh Province (15 districts)
  { name: 'Balkh',            nameLocal: 'بلخ',             province: 'Balkh' },
  { name: 'Charbolak',        nameLocal: 'چارپولک',         province: 'Balkh' },
  { name: 'Charkint',         nameLocal: 'چارکنت',          province: 'Balkh' },
  { name: 'Chimtal',          nameLocal: 'چمتال',           province: 'Balkh' },
  { name: 'Dawlatabad',       nameLocal: 'دولت آباد',       province: 'Balkh' },
  { name: 'Dihdadi',          nameLocal: 'دهدادی',          province: 'Balkh' },
  { name: 'Kaldar',           nameLocal: 'کلدار',           province: 'Balkh' },
  { name: 'Khulm',            nameLocal: 'خلم',             province: 'Balkh' },
  { name: 'Kishindih',        nameLocal: 'کشنده',           province: 'Balkh' },
  { name: 'Marmul',           nameLocal: 'مارمل',           province: 'Balkh' },
  { name: 'Mazar-i-Sharif',   nameLocal: 'مزارشريف',        province: 'Balkh' },
  { name: 'Nahri Shahi',      nameLocal: 'نهر شاهی',        province: 'Balkh' },
  { name: 'Sholgara',         nameLocal: 'شولگره',          province: 'Balkh' },
  { name: 'Shortepa',         nameLocal: 'شورتپه',          province: 'Balkh' },
  { name: 'Zari',             nameLocal: 'زاری',            province: 'Balkh' },

  // Bamyan Province (8 districts)
  { name: 'Bamyan',           nameLocal: 'باميان',          province: 'Bamyan' },
  { name: 'Kahmard',          nameLocal: 'کهمرد',           province: 'Bamyan' },
  { name: 'Panjab',           nameLocal: 'پنجاب',           province: 'Bamyan' },
  { name: 'Sayghan',          nameLocal: 'سيغان',           province: 'Bamyan' },
  { name: 'Shibar',           nameLocal: 'شيبر',            province: 'Bamyan' },
  { name: 'Waras',            nameLocal: 'ورس',             province: 'Bamyan' },
  { name: 'Yakawlang',        nameLocal: 'يکاولنگ',         province: 'Bamyan' },
  { name: 'Yakawlang 2',      nameLocal: 'يکاولنگ دوم',     province: 'Bamyan' },

  // Daykundi Province (8 districts)
  { name: 'Ishtarlay',        nameLocal: 'اشترلی',          province: 'Daykundi' },
  { name: 'Kijran',           nameLocal: 'کجران',           province: 'Daykundi' },
  { name: 'Khedir',           nameLocal: 'خدير',            province: 'Daykundi' },
  { name: 'Kitti',            nameLocal: 'گيتی',            province: 'Daykundi' },
  { name: 'Miramor',          nameLocal: 'ميرامور',         province: 'Daykundi' },
  { name: 'Nili',             nameLocal: 'نيلی',            province: 'Daykundi' },
  { name: 'Sangi Takht',      nameLocal: 'سنگ تخت',         province: 'Daykundi' },
  { name: 'Shahristan',       nameLocal: 'شهرستان',         province: 'Daykundi' },

  // Farah Province (11 districts)
  { name: 'Anar Dara',        nameLocal: 'اناردره',         province: 'Farah' },
  { name: 'Bakwa',            nameLocal: 'بکواه',           province: 'Farah' },
  { name: 'Bala Buluk',       nameLocal: 'بالابلوک',        province: 'Farah' },
  { name: 'Farah',            nameLocal: 'فراه',            province: 'Farah' },
  { name: 'Gulistan',         nameLocal: 'گلستان',          province: 'Farah' },
  { name: 'Khaki Safed',      nameLocal: 'خاک سفيد',        province: 'Farah' },
  { name: 'Lash wa Juwayn',   nameLocal: 'لاش و جوين',      province: 'Farah' },
  { name: 'Pur Chaman',       nameLocal: 'پرچمن',           province: 'Farah' },
  { name: 'Pusht Rod',        nameLocal: 'پشترود',          province: 'Farah' },
  { name: 'Qala-i-Kah',       nameLocal: 'قلعه کاه',        province: 'Farah' },
  { name: 'Shib Koh',         nameLocal: 'شيب کوه',         province: 'Farah' },

  // Faryab Province (14 districts)
  { name: 'Almar',            nameLocal: 'الما',            province: 'Faryab' },
  { name: 'Andkhoy',          nameLocal: 'اندخوی',          province: 'Faryab' },
  { name: 'Bilchiragh',       nameLocal: 'بلچراغ',          province: 'Faryab' },
  { name: 'Dawlat Abad',      nameLocal: 'دولت آباد',       province: 'Faryab' },
  { name: 'Gurziwan',         nameLocal: 'گرزيوان',         province: 'Faryab' },
  { name: 'Khani Char Bagh',  nameLocal: 'خان چارباغ',      province: 'Faryab' },
  { name: 'Khwaja Sabz Posh', nameLocal: 'خواجه سبزپوش',   province: 'Faryab' },
  { name: 'Kohistan',         nameLocal: 'کوهستان',         province: 'Faryab' },
  { name: 'Maymana',          nameLocal: 'ميمنه',           province: 'Faryab' },
  { name: 'Pashtun Kot',      nameLocal: 'پشتون کوت',       province: 'Faryab' },
  { name: 'Qaramqol',         nameLocal: 'قرمقل',           province: 'Faryab' },
  { name: 'Qaysar',           nameLocal: 'قيصار',           province: 'Faryab' },
  { name: 'Qurghan',          nameLocal: 'قرغان',           province: 'Faryab' },
  { name: 'Shirin Tagab',     nameLocal: 'شيرينتگاب',       province: 'Faryab' },

  // Ghazni Province (19 districts)
  { name: 'Ab Band',          nameLocal: 'آب بند',          province: 'Ghazni' },
  { name: 'Ajristan',         nameLocal: 'اجرستان',         province: 'Ghazni' },
  { name: 'Andar',            nameLocal: 'اندر',            province: 'Ghazni' },
  { name: 'Deh Yak',          nameLocal: 'ده يک',           province: 'Ghazni' },
  { name: 'Gelan',            nameLocal: 'گيلان',           province: 'Ghazni' },
  { name: 'Ghazni',           nameLocal: 'غزنی',            province: 'Ghazni' },
  { name: 'Giro',             nameLocal: 'گيرو',            province: 'Ghazni' },
  { name: 'Jaghatu',          nameLocal: 'جغتو',            province: 'Ghazni' },
  { name: 'Jaghori',          nameLocal: 'جاغوری',          province: 'Ghazni' },
  { name: 'Khogyani',         nameLocal: 'خوگيانی',         province: 'Ghazni' },
  { name: 'Khwaja Umari',     nameLocal: 'عمری',            province: 'Ghazni' },
  { name: 'Malistan',         nameLocal: 'مالستان',         province: 'Ghazni' },
  { name: 'Muqur',            nameLocal: 'مقر',             province: 'Ghazni' },
  { name: 'Nawa',             nameLocal: 'ناوه',            province: 'Ghazni' },
  { name: 'Nawur',            nameLocal: 'ناور',            province: 'Ghazni' },
  { name: 'Qarabagh',         nameLocal: 'قره باغ',         province: 'Ghazni' },
  { name: 'Rashidan',         nameLocal: 'رشيدان',          province: 'Ghazni' },
  { name: 'Waghaz',           nameLocal: 'واغز',            province: 'Ghazni' },
  { name: 'Zana Khan',        nameLocal: 'زنه خان',         province: 'Ghazni' },

  // Ghor Province (11 districts)
  { name: 'Chaghcharan',      nameLocal: 'چغچران',          province: 'Ghor' },
  { name: 'Charsada',         nameLocal: 'چارسده',          province: 'Ghor' },
  { name: 'Dawlat Yar',       nameLocal: 'دولت يار',        province: 'Ghor' },
  { name: 'Du Layna',         nameLocal: 'دولينه',          province: 'Ghor' },
  { name: 'Lal wa Sarjangal', nameLocal: 'لعل و سرجنگل',   province: 'Ghor' },
  { name: 'Marghab',          nameLocal: 'مرغاب',           province: 'Ghor' },
  { name: 'Pasaband',         nameLocal: 'پسابند',          province: 'Ghor' },
  { name: 'Saghar',           nameLocal: 'ساغر',            province: 'Ghor' },
  { name: 'Shahrak',          nameLocal: 'شهرک',            province: 'Ghor' },
  { name: 'Taywara',          nameLocal: 'تيوره',           province: 'Ghor' },
  { name: 'Tulak',            nameLocal: 'تولک',            province: 'Ghor' },

  // Helmand Province (14 districts)
  { name: 'Baghran',              nameLocal: 'باغران',          province: 'Helmand' },
  { name: 'Dishu',                nameLocal: 'ديشو',            province: 'Helmand' },
  { name: 'Garmsir',              nameLocal: 'گرمسير',          province: 'Helmand' },
  { name: 'Kajaki',               nameLocal: 'کجکی',            province: 'Helmand' },
  { name: 'Khanashin',            nameLocal: 'خاننشين',         province: 'Helmand' },
  { name: 'Lashkargah',           nameLocal: 'لشکرگاه',         province: 'Helmand' },
  { name: 'Marjah',               nameLocal: 'مارجه',           province: 'Helmand' },
  { name: 'Musa Qala',            nameLocal: 'موسی قلا',        province: 'Helmand' },
  { name: 'Nad Ali',              nameLocal: 'نادعلی',          province: 'Helmand' },
  { name: 'Nahri Saraj',          nameLocal: 'نهر سراج',        province: 'Helmand' },
  { name: 'Nawa-i-Barakzayi',     nameLocal: 'ناوه بارکزی',     province: 'Helmand' },
  { name: 'Nawzad',               nameLocal: 'نوزاد',           province: 'Helmand' },
  { name: 'Sangin',               nameLocal: 'سنگين',           province: 'Helmand' },
  { name: 'Washir',               nameLocal: 'واشير',           province: 'Helmand' },

  // Herat Province (16 districts)
  { name: 'Adraskan',         nameLocal: 'ادرسکن',          province: 'Herat' },
  { name: 'Chishti Sharif',   nameLocal: 'چشت شريف',        province: 'Herat' },
  { name: 'Farsi',            nameLocal: 'فارسی',           province: 'Herat' },
  { name: 'Ghoryan',          nameLocal: 'غوريان',          province: 'Herat' },
  { name: 'Gulran',           nameLocal: 'گلران',           province: 'Herat' },
  { name: 'Guzara',           nameLocal: 'گذره',            province: 'Herat' },
  { name: 'Herat',            nameLocal: 'هرات',            province: 'Herat' },
  { name: 'Injil',            nameLocal: 'انجيل',           province: 'Herat' },
  { name: 'Karukh',           nameLocal: 'کرخ',             province: 'Herat' },
  { name: 'Kohsan',           nameLocal: 'کهسان',           province: 'Herat' },
  { name: 'Kushk',            nameLocal: 'کشک',             province: 'Herat' },
  { name: 'Kushki Kuhna',     nameLocal: 'کشک کهنه',        province: 'Herat' },
  { name: 'Obe',              nameLocal: 'اوبه',            province: 'Herat' },
  { name: 'Pashtun Zarghun',  nameLocal: 'پشتون زرغون',     province: 'Herat' },
  { name: 'Shindand',         nameLocal: 'شيندند',          province: 'Herat' },
  { name: 'Zinda Jan',        nameLocal: 'زنده جان',        province: 'Herat' },

  // Jawzjan Province (11 districts)
  { name: 'Aqcha',            nameLocal: 'آقچه',            province: 'Jawzjan' },
  { name: 'Darzab',           nameLocal: 'درزاب',           province: 'Jawzjan' },
  { name: 'Fayzabad',         nameLocal: 'فيض آباد',        province: 'Jawzjan' },
  { name: 'Khamyab',          nameLocal: 'خوم آب',          province: 'Jawzjan' },
  { name: 'Khaniqa',          nameLocal: 'خانقاه',          province: 'Jawzjan' },
  { name: 'Khwaja Du Koh',    nameLocal: 'خواجه دوکوه',     province: 'Jawzjan' },
  { name: 'Mardyan',          nameLocal: 'مرديان',          province: 'Jawzjan' },
  { name: 'Mingajik',         nameLocal: 'منگجک',           province: 'Jawzjan' },
  { name: 'Qarqin',           nameLocal: 'قرقين',           province: 'Jawzjan' },
  { name: 'Qush Tepa',        nameLocal: 'قوش تپه',         province: 'Jawzjan' },
  { name: 'Sheberghan',       nameLocal: 'شبرغان',          province: 'Jawzjan' },

  // Kabul Province (15 districts)
  { name: 'Bagrami',          nameLocal: 'بگرامی',          province: 'Kabul' },
  { name: 'Chahar Asyab',     nameLocal: 'چهارآسياب',       province: 'Kabul' },
  { name: 'Deh Sabz',         nameLocal: 'دهسبز',           province: 'Kabul' },
  { name: 'Farza',            nameLocal: 'فرزه',            province: 'Kabul' },
  { name: 'Guldara',          nameLocal: 'گلدره',           province: 'Kabul' },
  { name: 'Istalif',          nameLocal: 'استاليف',         province: 'Kabul' },
  { name: 'Kabul',            nameLocal: 'کابل',            province: 'Kabul' },
  { name: 'Kalakan',          nameLocal: 'کلکان',           province: 'Kabul' },
  { name: 'Khaki Jabbar',     nameLocal: 'خاک جبار',        province: 'Kabul' },
  { name: 'Mir Bacha Kot',    nameLocal: 'ميربچه کوت',      province: 'Kabul' },
  { name: 'Mussahi',          nameLocal: 'موسهی',           province: 'Kabul' },
  { name: 'Paghman',          nameLocal: 'پغمان',           province: 'Kabul' },
  { name: 'Qarabagh',         nameLocal: 'قره باغ',         province: 'Kabul' },
  { name: 'Shakardara',       nameLocal: 'شکردره',          province: 'Kabul' },
  { name: 'Surobi',           nameLocal: 'سروبی',           province: 'Kabul' },

  // Kandahar Province (18 districts)
  { name: 'Arghandab',        nameLocal: 'ارغنداب',         province: 'Kandahar' },
  { name: 'Arghistan',        nameLocal: 'ارغستان',         province: 'Kandahar' },
  { name: 'Daman',            nameLocal: 'دامان',           province: 'Kandahar' },
  { name: 'Dand',             nameLocal: 'دند',             province: 'Kandahar' },
  { name: 'Ghorak',           nameLocal: 'غورک',            province: 'Kandahar' },
  { name: 'Kandahar',         nameLocal: 'کندهار',          province: 'Kandahar' },
  { name: 'Khakrez',          nameLocal: 'خاکريز',          province: 'Kandahar' },
  { name: 'Maiwand',          nameLocal: 'ميوند',           province: 'Kandahar' },
  { name: 'Maruf',            nameLocal: 'معروف',           province: 'Kandahar' },
  { name: 'Miyanishin',       nameLocal: 'ميانشين',         province: 'Kandahar' },
  { name: 'Nesh',             nameLocal: 'نش',              province: 'Kandahar' },
  { name: 'Panjwayi',         nameLocal: 'پنجوايی',         province: 'Kandahar' },
  { name: 'Reg',              nameLocal: 'ريگ',             province: 'Kandahar' },
  { name: 'Shah Wali Kot',    nameLocal: 'شاه ولی کوت',     province: 'Kandahar' },
  { name: 'Shorabak',         nameLocal: 'شورابک',          province: 'Kandahar' },
  { name: 'Spin Boldak',      nameLocal: 'سپين بولدک',      province: 'Kandahar' },
  { name: 'Takhta-pul',       nameLocal: 'تخته پل',         province: 'Kandahar' },
  { name: 'Zhari',            nameLocal: 'ژړی',             province: 'Kandahar' },

  // Kapisa Province (7 districts)
  { name: 'Alasay',               nameLocal: 'الهسايی',          province: 'Kapisa' },
  { name: 'Hesa Awal Kohistan',   nameLocal: 'حصه اول کوهستان',  province: 'Kapisa' },
  { name: 'Hesa Duwum Kohistan',  nameLocal: 'حصه دوم کوهستان',  province: 'Kapisa' },
  { name: 'Koh Band',             nameLocal: 'کوه بند',           province: 'Kapisa' },
  { name: 'Mahmud Raqi',          nameLocal: 'محمود راقی',        province: 'Kapisa' },
  { name: 'Nijrab',               nameLocal: 'نجراب',             province: 'Kapisa' },
  { name: 'Tagab',                nameLocal: 'تگاب',              province: 'Kapisa' },

  // Khost Province (13 districts)
  { name: 'Bak',              nameLocal: 'باک',             province: 'Khost' },
  { name: 'Gurbuz',           nameLocal: 'گوربز',           province: 'Khost' },
  { name: 'Jaji Maydan',      nameLocal: 'جاجی ميدان',      province: 'Khost' },
  { name: 'Khost',            nameLocal: 'خوست',            province: 'Khost' },
  { name: 'Mandozayi',        nameLocal: 'منډوزی',          province: 'Khost' },
  { name: 'Musa Khel',        nameLocal: 'موسی خيل',        province: 'Khost' },
  { name: 'Nadir Shah Kot',   nameLocal: 'نادرشاه کوت',     province: 'Khost' },
  { name: 'Qalandar',         nameLocal: 'قلندر',           province: 'Khost' },
  { name: 'Sabari',           nameLocal: 'صبری',            province: 'Khost' },
  { name: 'Shamal',           nameLocal: 'شمول',            province: 'Khost' },
  { name: 'Spera',            nameLocal: 'سپيره',           province: 'Khost' },
  { name: 'Tani',             nameLocal: 'تنی',             province: 'Khost' },
  { name: 'Tirazayi',         nameLocal: 'تيريزائی',        province: 'Khost' },

  // Kunar Province (16 districts)
  { name: 'Asadabad',         nameLocal: 'اسدآباد',         province: 'Kunar' },
  { name: 'Bar Kunar',        nameLocal: 'برکنر',           province: 'Kunar' },
  { name: 'Chapa Dara',       nameLocal: 'چپه دره',         province: 'Kunar' },
  { name: 'Chawkay',          nameLocal: 'چوکی',            province: 'Kunar' },
  { name: 'Dangam',           nameLocal: 'دانگام',          province: 'Kunar' },
  { name: 'Dara-i-Pech',      nameLocal: 'دره پيچ',         province: 'Kunar' },
  { name: 'Ghaziabad',        nameLocal: 'غازی آباد',       province: 'Kunar' },
  { name: 'Khas Kunar',       nameLocal: 'خاصکنر',          province: 'Kunar' },
  { name: 'Marawara',         nameLocal: 'مروره',           province: 'Kunar' },
  { name: 'Narang Aw Badil',  nameLocal: 'نارنگ',           province: 'Kunar' },
  { name: 'Nari',             nameLocal: 'ناری',            province: 'Kunar' },
  { name: 'Nurgal',           nameLocal: 'نورگل',           province: 'Kunar' },
  { name: 'Shaigal',          nameLocal: 'شيگل',            province: 'Kunar' },
  { name: 'Shultan',          nameLocal: 'شلتن',            province: 'Kunar' },
  { name: 'Sirkani',          nameLocal: 'سرکانی',          province: 'Kunar' },
  { name: 'Wata Pur',         nameLocal: 'وتهپور',          province: 'Kunar' },

  // Kunduz Province (7 districts)
  { name: 'Ali Abad',         nameLocal: 'علی آباد',        province: 'Kunduz' },
  { name: 'Archi',            nameLocal: 'ارچی',            province: 'Kunduz' },
  { name: 'Chardara',         nameLocal: 'چهاردره',         province: 'Kunduz' },
  { name: 'Imam Sahib',       nameLocal: 'امام صاحب',       province: 'Kunduz' },
  { name: 'Khan Abad',        nameLocal: 'خان آباد',        province: 'Kunduz' },
  { name: 'Kunduz',           nameLocal: 'کندوز',           province: 'Kunduz' },
  { name: 'Qalay-i-Zal',      nameLocal: 'قلعه ذال',        province: 'Kunduz' },

  // Laghman Province (5 districts)
  { name: 'Alingar',          nameLocal: 'علينگار',         province: 'Laghman' },
  { name: 'Alishing',         nameLocal: 'علی شنگ',         province: 'Laghman' },
  { name: 'Dawlat Shah',      nameLocal: 'دولت شاه',        province: 'Laghman' },
  { name: 'Mehtarlam',        nameLocal: 'مهترلام',         province: 'Laghman' },
  { name: 'Qarghayi',         nameLocal: 'قرغهای',          province: 'Laghman' },

  // Logar Province (7 districts)
  { name: 'Azra',             nameLocal: 'ازره',            province: 'Logar' },
  { name: 'Baraki Barak',     nameLocal: 'برکی برک',        province: 'Logar' },
  { name: 'Charkh',           nameLocal: 'چرخ',             province: 'Logar' },
  { name: 'Kharwar',          nameLocal: 'خروار',           province: 'Logar' },
  { name: 'Khoshi',           nameLocal: 'خوشی',            province: 'Logar' },
  { name: 'Mohammad Agha',    nameLocal: 'محمدآغه',         province: 'Logar' },
  { name: 'Pul-i-Alam',       nameLocal: 'پل علم',          province: 'Logar' },

  // Nangarhar Province (22 districts)
  { name: 'Achin',            nameLocal: 'اچين',            province: 'Nangarhar' },
  { name: 'Bati Kot',         nameLocal: 'بتيکوت',          province: 'Nangarhar' },
  { name: 'Bihsud',           nameLocal: 'بهسود',           province: 'Nangarhar' },
  { name: 'Chaparhar',        nameLocal: 'چپرهار',          province: 'Nangarhar' },
  { name: 'Darai Nur',        nameLocal: 'دره نور',         province: 'Nangarhar' },
  { name: 'Deh Bala',         nameLocal: 'ده بالا',         province: 'Nangarhar' },
  { name: 'Dur Baba',         nameLocal: 'دربابا',          province: 'Nangarhar' },
  { name: 'Goshta',           nameLocal: 'گوشته',           province: 'Nangarhar' },
  { name: 'Hisarak',          nameLocal: 'حصارک',           province: 'Nangarhar' },
  { name: 'Jalalabad',        nameLocal: 'جلال آباد',       province: 'Nangarhar' },
  { name: 'Kama',             nameLocal: 'کامه',            province: 'Nangarhar' },
  { name: 'Khogyani',         nameLocal: 'خوگيانی',         province: 'Nangarhar' },
  { name: 'Kot',              nameLocal: 'کوت',             province: 'Nangarhar' },
  { name: 'Kuz Kunar',        nameLocal: 'کوزکنر',          province: 'Nangarhar' },
  { name: 'Lal Pur',          nameLocal: 'لعل پور',         province: 'Nangarhar' },
  { name: 'Momand Dara',      nameLocal: 'مهمنددره',        province: 'Nangarhar' },
  { name: 'Nazyan',           nameLocal: 'نازيان',          province: 'Nangarhar' },
  { name: 'Pachir Aw Agam',   nameLocal: 'پچيرواگام',       province: 'Nangarhar' },
  { name: 'Rodat',            nameLocal: 'رودات',           province: 'Nangarhar' },
  { name: 'Sherzad',          nameLocal: 'شيرزاد',          province: 'Nangarhar' },
  { name: 'Shinwar',          nameLocal: 'شينوار',          province: 'Nangarhar' },
  { name: 'Surkh Rod',        nameLocal: 'سرخ رود',         province: 'Nangarhar' },

  // Nimroz Province (5 districts)
  { name: 'Chahar Burjak',    nameLocal: 'چهاربرجک',        province: 'Nimroz' },
  { name: 'Chakhansur',       nameLocal: 'چخانسور',         province: 'Nimroz' },
  { name: 'Kang',             nameLocal: 'کنگ',             province: 'Nimroz' },
  { name: 'Khash Rod',        nameLocal: 'خاش رود',         province: 'Nimroz' },
  { name: 'Zaranj',           nameLocal: 'زرنج',            province: 'Nimroz' },

  // Nuristan Province (8 districts)
  { name: 'Barg-i Matal',     nameLocal: 'برگ متال',        province: 'Nuristan' },
  { name: 'Du Ab',            nameLocal: 'دوآب',            province: 'Nuristan' },
  { name: 'Kamdesh',          nameLocal: 'کامديش',          province: 'Nuristan' },
  { name: 'Mandol',           nameLocal: 'مندول',           province: 'Nuristan' },
  { name: 'Nurgram',          nameLocal: 'نورگرام',         province: 'Nuristan' },
  { name: 'Parun',            nameLocal: 'پارون',           province: 'Nuristan' },
  { name: 'Wama',             nameLocal: 'واما',            province: 'Nuristan' },
  { name: 'Waygal',           nameLocal: 'واي گل',          province: 'Nuristan' },

  // Paktia Province (15 districts)
  { name: 'Ahmad Aba',        nameLocal: 'احمدآباد',        province: 'Paktia' },
  { name: 'Ahmadkhel',        nameLocal: 'علی خيل',         province: 'Paktia' },
  { name: 'Chamkani',         nameLocal: 'چاوک',            province: 'Paktia' },
  { name: 'Dand Aw Patan',    nameLocal: 'دند پتان',        province: 'Paktia' },
  { name: 'Gardez',           nameLocal: 'گرديز',           province: 'Paktia' },
  { name: 'Gerda Serai',      nameLocal: 'گرده ثيری',       province: 'Paktia' },
  { name: 'Janikhel',         nameLocal: 'جانيخيل',         province: 'Paktia' },
  { name: 'Laja Mangal',      nameLocal: 'لجه منگل',        province: 'Paktia' },
  { name: 'Mirzaka',          nameLocal: 'ميرزکه',          province: 'Paktia' },
  { name: 'Rohani Baba',      nameLocal: 'روهانی بابا',     province: 'Paktia' },
  { name: 'Said Karam',       nameLocal: 'سيد کرم',         province: 'Paktia' },
  { name: 'Shwak',            nameLocal: 'شواک',            province: 'Paktia' },
  { name: 'Zadran',           nameLocal: 'زدران',           province: 'Paktia' },
  { name: 'Zazi (Jaji)',      nameLocal: 'جاجی',            province: 'Paktia' },
  { name: 'Zurmat',           nameLocal: 'زرمت',            province: 'Paktia' },

  // Paktika Province (19 districts)
  { name: 'Barmal',           nameLocal: 'برمل',            province: 'Paktika' },
  { name: 'Dila',             nameLocal: 'ديله و خوشامند',  province: 'Paktika' },
  { name: 'Gayan',            nameLocal: 'گيان',            province: 'Paktika' },
  { name: 'Gomal',            nameLocal: 'گومل',            province: 'Paktika' },
  { name: 'Janikhel',         nameLocal: 'جانی خيل',        province: 'Paktika' },
  { name: 'Khairkot',         nameLocal: 'زرغون شهر',       province: 'Paktika' },
  { name: 'Mata Khan',        nameLocal: 'متاخان',          province: 'Paktika' },
  { name: 'Nika',             nameLocal: 'نکه',             province: 'Paktika' },
  { name: 'Omna',             nameLocal: 'اومنه',           province: 'Paktika' },
  { name: 'Sar Hawza',        nameLocal: 'سرحوضه',          province: 'Paktika' },
  { name: 'Sharana',          nameLocal: 'شرن',             province: 'Paktika' },
  { name: 'Surobi',           nameLocal: 'سروبی',           province: 'Paktika' },
  { name: 'Terwa',            nameLocal: 'تروو',            province: 'Paktika' },
  { name: 'Urgun',            nameLocal: 'ارگون',           province: 'Paktika' },
  { name: 'Wazakhwa',         nameLocal: 'وازهخواه',        province: 'Paktika' },
  { name: 'Wor Mamay',        nameLocal: 'ورممی',           province: 'Paktika' },
  { name: 'Yahyakhel',        nameLocal: 'يحيی خيل',        province: 'Paktika' },
  { name: 'Yusufkhel',        nameLocal: 'يوسف خيل',        province: 'Paktika' },
  { name: 'Zerok',            nameLocal: 'زيروک',           province: 'Paktika' },

  // Panjshir Province (8 districts)
  { name: 'Abshar',           nameLocal: 'آبشار',           province: 'Panjshir' },
  { name: 'Anaba',            nameLocal: 'انابه',           province: 'Panjshir' },
  { name: 'Bazarak',          nameLocal: 'بازارک',          province: 'Panjshir' },
  { name: 'Darah',            nameLocal: 'دره',             province: 'Panjshir' },
  { name: 'Khenj',            nameLocal: 'خنج',             province: 'Panjshir' },
  { name: 'Paryan',           nameLocal: 'پريان',           province: 'Panjshir' },
  { name: 'Rokha',            nameLocal: 'روخه',            province: 'Panjshir' },
  { name: 'Shotul',           nameLocal: 'شتل',             province: 'Panjshir' },

  // Parwan Province (10 districts)
  { name: 'Bagram',           nameLocal: 'بگرام',           province: 'Parwan' },
  { name: 'Charikar',         nameLocal: 'چاريکار',         province: 'Parwan' },
  { name: 'Ghorband',         nameLocal: 'غوربند',          province: 'Parwan' },
  { name: 'Jabal Saraj',      nameLocal: 'جبلسراج',         province: 'Parwan' },
  { name: 'Kohi Safi',        nameLocal: 'کوه صافی',        province: 'Parwan' },
  { name: 'Salang',           nameLocal: 'سالنگ',           province: 'Parwan' },
  { name: 'Sayed Khel',       nameLocal: 'سيدخيل',          province: 'Parwan' },
  { name: 'Sheikh Ali',       nameLocal: 'شيخ علی',         province: 'Parwan' },
  { name: 'Shinwari',         nameLocal: 'شينواری',         province: 'Parwan' },
  { name: 'Surkhi Parsa',     nameLocal: 'سرخ پارسا',       province: 'Parwan' },

  // Samangan Province (7 districts)
  { name: 'Aybak',            nameLocal: 'آيبک',            province: 'Samangan' },
  { name: 'Darah Sof Bala',   nameLocal: 'دره صوف بالا',    province: 'Samangan' },
  { name: 'Darah Sof Payan',  nameLocal: 'دره صوف پايين',   province: 'Samangan' },
  { name: 'Feroz Nakhchir',   nameLocal: 'فيروزنخچير',      province: 'Samangan' },
  { name: 'Hazrat Sultan',    nameLocal: 'حضرت سلطان',      province: 'Samangan' },
  { name: 'Khuram wa Sarbagh',nameLocal: 'خرم و سارباغ',    province: 'Samangan' },
  { name: 'Ruyi Du Ab',       nameLocal: 'روی دوآب',        province: 'Samangan' },

  // Sar-e-Pol Province (7 districts)
  { name: 'Balkhab',          nameLocal: 'بلخاب',           province: 'Sar-e-Pol' },
  { name: 'Gosfandi',         nameLocal: 'گوسفندی',         province: 'Sar-e-Pol' },
  { name: 'Kohistanat',       nameLocal: 'کوهستانات',       province: 'Sar-e-Pol' },
  { name: 'Sancharak',        nameLocal: 'سانچارک',         province: 'Sar-e-Pol' },
  { name: 'Sar-e-Pol',        nameLocal: 'سرپل',            province: 'Sar-e-Pol' },
  { name: 'Sayyad',           nameLocal: 'صياد',            province: 'Sar-e-Pol' },
  { name: 'Sozma Qala',       nameLocal: 'سوزمه قلعه',      province: 'Sar-e-Pol' },

  // Takhar Province (17 districts)
  { name: 'Baharak',          nameLocal: 'بهارک',           province: 'Takhar' },
  { name: 'Bangi',            nameLocal: 'بنگی',            province: 'Takhar' },
  { name: 'Chah Ab',          nameLocal: 'چاه آب',          province: 'Takhar' },
  { name: 'Chal',             nameLocal: 'چال',             province: 'Takhar' },
  { name: 'Darqad',           nameLocal: 'درقد',            province: 'Takhar' },
  { name: 'Dashti Qala',      nameLocal: 'دشت قلعه',        province: 'Takhar' },
  { name: 'Farkhar',          nameLocal: 'فرخار',           province: 'Takhar' },
  { name: 'Hazar Sumuch',     nameLocal: 'هزار سموچ',       province: 'Takhar' },
  { name: 'Ishkamish',        nameLocal: 'اشکمش',           province: 'Takhar' },
  { name: 'Kalafgan',         nameLocal: 'کلفگان',          province: 'Takhar' },
  { name: 'Khwaja Bahauddin', nameLocal: 'خواجه بهاءالدين', province: 'Takhar' },
  { name: 'Khwaja Ghar',      nameLocal: 'خواجه غار',       province: 'Takhar' },
  { name: 'Namak Ab',         nameLocal: 'نمک آب',          province: 'Takhar' },
  { name: 'Rustaq',           nameLocal: 'روستاق',          province: 'Takhar' },
  { name: 'Taluqan',          nameLocal: 'تالقان',          province: 'Takhar' },
  { name: 'Warsaj',           nameLocal: 'ورسج',            province: 'Takhar' },
  { name: 'Yangi Qala',       nameLocal: 'ينگی قلعه',       province: 'Takhar' },

  // Urozgan Province (6 districts)
  { name: 'Chora',            nameLocal: 'چوره',            province: 'Urozgan' },
  { name: 'Deh Rawood',       nameLocal: 'دهراوود',         province: 'Urozgan' },
  { name: 'Gizab',            nameLocal: 'گيزاب',           province: 'Urozgan' },
  { name: 'Khas Uruzgan',     nameLocal: 'خاص روزگان',      province: 'Urozgan' },
  { name: 'Shahidi Hassas',   nameLocal: 'شهيد حساس',       province: 'Urozgan' },
  { name: 'Tarinkot',         nameLocal: 'ترينکوت',         province: 'Urozgan' },

  // Wardak Province (9 districts)
  { name: 'Chaki Wardak',         nameLocal: 'چک وردک',         province: 'Wardak' },
  { name: 'Day Mirdad',           nameLocal: 'دای ميرداد',      province: 'Wardak' },
  { name: 'Hisa-i-Awali Bihsud',  nameLocal: 'حصه اول بهسود',   province: 'Wardak' },
  { name: 'Jaghatu',              nameLocal: 'جغتو',            province: 'Wardak' },
  { name: 'Jalrez',               nameLocal: 'جلريز',           province: 'Wardak' },
  { name: 'Maidan Shar',          nameLocal: 'ميدان شهر',       province: 'Wardak' },
  { name: 'Markazi Bihsud',       nameLocal: 'مرکز بهسود',      province: 'Wardak' },
  { name: 'Nirkh',                nameLocal: 'نرخ',             province: 'Wardak' },
  { name: 'Saydabad',             nameLocal: 'سيدآباد',         province: 'Wardak' },

  // Zabul Province (11 districts)
  { name: 'Arghandab',        nameLocal: 'ارغنداب',         province: 'Zabul' },
  { name: 'Atghar',           nameLocal: 'اتغر',            province: 'Zabul' },
  { name: 'Daychopan',        nameLocal: 'دايچوپان',        province: 'Zabul' },
  { name: 'Kakar',            nameLocal: 'کاکر',            province: 'Zabul' },
  { name: 'Mezana',           nameLocal: 'ميزان',           province: 'Zabul' },
  { name: 'Naw Bahar',        nameLocal: 'نوبهار',          province: 'Zabul' },
  { name: 'Qalat',            nameLocal: 'قلات',            province: 'Zabul' },
  { name: 'Shah Joy',         nameLocal: 'شاه جوی',         province: 'Zabul' },
  { name: 'Shamulzayi',       nameLocal: 'شملزائی',         province: 'Zabul' },
  { name: 'Shinkay',          nameLocal: 'شينکی',           province: 'Zabul' },
  { name: 'Tarnak Aw Jaldak', nameLocal: 'ترنگ و جلدک',     province: 'Zabul' },
] as const

/**
 * Returns all districts belonging to the specified province.
 * Returns empty array if province has no districts in the dataset.
 */
export function getDistrictsByProvince(province: AfghanProvince): AfghanDistrict[] {
  return AFGHAN_DISTRICTS.filter(d => d.province === province)
}
